// The registry: every word set down in Crosslink — Polysemous Words.
// Generated from Crosslink Design Documents/words.py. Senses only; the
// constructor's notes on which pairs cross well stay in the source file,
// because they are notes about puzzles not yet built.
window.CROSSLINK = window.CROSSLINK || {};
window.CROSSLINK.registry = {
  PITCH: [["Sport", "a throw, and the field played on"], ["Music", "how high a note sounds"], ["Substance", "black tar; pitch-black"], ["Trade", "a sales pitch"], ["Building", "the slope of a roof"], ["Action", "to pitch a tent"], ["Nautical", "a ship pitching in swell"]],
  STOCK: [["Food", "the broth a soup is built on"], ["Money", "shares in a company"], ["Animal", "livestock"], ["Military", "the wooden part of a gun"], ["Abstract", "descent, as in 'of good stock'"], ["Trade", "goods held in reserve"], ["Plant", "the flower, and a grafting rootstock"], ["Law", "the stocks, a punishment"]],
  BAR: [["Place", "where drink is served"], ["Artifact", "a rod of metal"], ["Music", "a measure of written music"], ["Law", "the profession, and the bar of a court"], ["Nature", "a sandbar at a river mouth"], ["Action", "to bar the way"], ["Measure", "a bar of pressure"]],
  KEY: [["Artifact", "what opens a lock"], ["Music", "the key a piece is written in"], ["Tool", "a piano or typewriter key"], ["Language", "a legend or answer key"], ["Nature", "a low island; the Florida Keys"], ["Abstract", "crucial, the key point"]],
  BRIDGE: [["Building", "the span over water"], ["Game", "the card game"], ["Body", "the bridge of the nose"], ["Music", "the piece under violin strings, and a song's middle section"], ["Nautical", "where a ship is commanded from"], ["Science", "dentistry; a dental bridge"], ["Action", "to bridge a gap"]],
  HAND: [["Body", "the end of the arm"], ["Artifact", "a clock hand"], ["Game", "the cards you hold"], ["Person", "a worker; all hands on deck"], ["Language", "handwriting"], ["Action", "applause; a big hand"], ["Measure", "the height of a horse"]],
  HEAD: [["Body", "what sits on the neck"], ["Person", "the person in charge"], ["Food", "the foam on a beer"], ["Nautical", "the lavatory on a boat"], ["Nature", "the source of a river, and a headland"], ["Measure", "cattle counted by the head"], ["Action", "to head somewhere"]],
  STRIKE: [["Action", "to hit"], ["Trade", "workers downing tools"], ["Sport", "in baseball, and in bowling"], ["Money", "to strike a coin"], ["Nature", "an oil strike; a discovery"], ["Time", "a clock striking the hour"], ["Military", "an air strike"]],
  RING: [["Shape", "a circle"], ["Artifact", "jewellery for a finger"], ["Music", "the sound a bell makes"], ["Sport", "where boxers fight"], ["Group", "a criminal ring"], ["Language", "a telephone call"], ["Plant", "the growth rings of a tree"]],
  SHOT: [["Military", "a fired round"], ["Art", "a photograph or a camera shot"], ["Science", "an injection"], ["Abstract", "an attempt; give it a shot"], ["Drink", "a small measure of spirits"], ["Substance", "lead pellets"], ["Sport", "the shot put"]],
  CHARGE: [["Money", "a fee"], ["Science", "electrical charge"], ["Military", "a cavalry charge"], ["Law", "a criminal charge"], ["Person", "someone in your care"], ["Action", "to load a weapon or a battery"]],
  CELL: [["Building", "a room in a prison, and a monk's room"], ["Science", "the unit of life"], ["Artifact", "a battery cell"], ["Group", "a resistance or terrorist cell"], ["Language", "a cell in a spreadsheet or table"], ["Body", "a blood cell"]],
  MOLE: [["Animal", "the burrowing creature"], ["Body", "a dark mark on skin"], ["Person", "a spy inside an organisation"], ["Measure", "the chemist's unit of quantity"], ["Building", "a breakwater or pier"], ["Food", "the Mexican sauce"]],
  SHELL: [["Animal", "what a mollusc lives in"], ["Military", "artillery ammunition"], ["Building", "the frame of a building"], ["Food", "a pastry case"], ["Science", "an electron shell"], ["Language", "a command shell"]],
  TRUNK: [["Plant", "the stem of a tree"], ["Animal", "an elephant's nose"], ["Artifact", "a travelling chest"], ["Vehicle", "the boot of a car"], ["Body", "the torso"], ["Place", "a trunk road or trunk line"]],
  WING: [["Animal", "what a bird flies with"], ["Vehicle", "an aircraft wing"], ["Building", "a wing of a house"], ["Abstract", "a political wing"], ["Place", "the wings of a theatre"], ["Sport", "a winger's position"]],
  CRACK: [["Shape", "a fissure"], ["Music", "a sharp sound"], ["Language", "a joke; to crack wise"], ["Substance", "the drug"], ["Abstract", "an attempt; have a crack"], ["Attribute", "expert; a crack shot"]],
  CROWN: [["Artifact", "what a monarch wears"], ["Body", "the top of the head"], ["Science", "a cap on a tooth"], ["Money", "the coin, and the currency"], ["Plant", "the top of a tree"], ["Law", "the Crown as the state"]],
  LEAD: [["Substance", "the soft grey metal"], ["Action", "to guide"], ["Artifact", "a dog's lead"], ["Abstract", "a clue for an investigator"], ["Sport", "the front position"], ["Tool", "the graphite in a pencil"]],
  SCALE: [["Animal", "what covers a fish"], ["Tool", "the instrument that weighs"], ["Music", "the ladder of notes"], ["Measure", "a map's ratio"], ["Action", "to climb"], ["Substance", "limescale in a kettle"]],
  DRAUGHT: [["Nature", "a current of air"], ["Drink", "beer served from the cask"], ["Military", "conscription (US draft)"], ["Language", "a preliminary version"], ["Nautical", "how deep a ship sits"], ["Animal", "a draught horse"], ["Game", "the game of draughts"]],
  FIGURE: [["Measure", "a number"], ["Body", "the shape of a person"], ["Person", "a notable person"], ["Language", "an illustration in a book"], ["Action", "to reckon; I figure"], ["Art", "a figure in a dance"]],
  RUN: [["Action", "to move fast on foot"], ["Textile", "a ladder in a stocking"], ["Sport", "a run in cricket or baseball"], ["Trade", "to run a business"], ["Nature", "a stream; a salmon run"], ["Language", "a print run"]],
  CAPITAL: [["Place", "the chief city"], ["Money", "funds and assets"], ["Language", "an upper-case letter"], ["Building", "the carved top of a column"], ["Law", "punishable by death"]],
  COURT: [["Law", "where a case is heard"], ["Group", "a monarch's household"], ["Sport", "where tennis is played"], ["Place", "a courtyard"], ["Action", "to court someone"]],
  CLUB: [["Artifact", "a heavy stick"], ["Group", "a society"], ["Place", "a nightclub"], ["Sport", "a golf club"], ["Game", "the card suit"]],
  PORT: [["Place", "a harbour"], ["Drink", "the fortified wine"], ["Nautical", "the left side of a ship"], ["Language", "a socket on a machine"], ["Action", "to port software across"]],
  BAY: [["Nature", "an inlet of the sea"], ["Plant", "the laurel; bay leaves"], ["Animal", "a reddish-brown horse"], ["Action", "to howl; hounds baying"], ["Building", "a loading bay or bay window"]],
  BILL: [["Money", "an invoice, and a banknote"], ["Animal", "a bird's beak"], ["Law", "a proposed act of parliament"], ["Language", "a poster; to bill a show"], ["Textile", "the brim of a cap"]],
  BOARD: [["Artifact", "a plank of wood"], ["Group", "the directors of a company"], ["Food", "meals; room and board"], ["Action", "to board a ship"], ["Game", "the surface a game is played on"]],
  BOLT: [["Artifact", "a threaded fastener"], ["Nature", "a bolt of lightning"], ["Action", "to bolt; to run away"], ["Textile", "a roll of cloth"], ["Military", "a crossbow bolt"]],
  SOUND: [["Music", "what the ear hears"], ["Attribute", "solid, healthy, sound reasoning"], ["Nature", "a strait of water; Puget Sound"], ["Nautical", "to sound the depth"], ["Action", "to sound out"]],
  SPRING: [["Time", "the season"], ["Nature", "water rising from the ground"], ["Artifact", "a coil of metal"], ["Action", "to leap"], ["Abstract", "the origin of a thing"]],
  BANK: [["Nature", "the edge of a river"], ["Money", "where money is kept"], ["Artifact", "a bank of oars, lights, switches"], ["Action", "to bank an aircraft"], ["Abstract", "to bank on something"]],
  TABLE: [["Artifact", "the furniture"], ["Language", "a grid of data"], ["Nature", "a tableland or plateau; the water table"], ["Law", "to table a motion"], ["Food", "the table one eats at"]],
  HOST: [["Person", "one who receives guests"], ["Measure", "a great multitude"], ["Science", "the organism a parasite lives on"], ["Religion", "the communion wafer"], ["Military", "an army; the heavenly host"]],
  MEDIUM: [["Measure", "the middle size"], ["Person", "one who speaks to the dead"], ["Language", "a means of communication"], ["Art", "the material an artist works in"], ["Science", "a growth medium"]],
  BATTERY: [["Artifact", "what stores charge"], ["Law", "assault and battery"], ["Military", "a group of guns"], ["Sport", "the pitcher and catcher together"], ["Abstract", "a battery of tests"]],
  COMPOUND: [["Science", "a chemical combination"], ["Place", "a walled enclosure"], ["Action", "to make worse; to compound a problem"], ["Language", "a compound word"], ["Money", "compound interest"]],
  BEAR: [["Animal", "the large mammal"], ["Action", "to carry"], ["Abstract", "to endure"], ["Money", "a falling market"], ["Science", "to give birth to"]],
  BULL: [["Animal", "the male of cattle"], ["Money", "a rising market"], ["Religion", "a papal bull"], ["Abstract", "nonsense"], ["Sport", "the bullseye"]],
  HORN: [["Body", "what grows on a bull's head"], ["Music", "the brass instrument"], ["Artifact", "a car horn"], ["Nature", "a cape; Cape Horn"], ["Drink", "a drinking horn"]],
  EYE: [["Body", "the organ of sight"], ["Tool", "the eye of a needle"], ["Nature", "the calm centre of a storm"], ["Plant", "the eye of a potato"], ["Textile", "a hook and eye"]],
  TONGUE: [["Body", "the organ in the mouth"], ["Language", "a language; the mother tongue"], ["Textile", "the flap under a shoelace"], ["Nature", "a spit of land"], ["Artifact", "the clapper of a bell"]],
  BOW: [["Military", "the weapon that fires arrows"], ["Music", "what draws across violin strings"], ["Textile", "a tied ribbon"], ["Action", "to bend at the waist"], ["Nautical", "the front of a ship"]],
  CHIP: [["Food", "a fried potato"], ["Science", "a silicon chip"], ["Game", "a gambling token"], ["Object", "a fragment broken off"], ["Sport", "a chip shot"]],
  JAM: [["Food", "fruit preserve"], ["Vehicle", "a traffic jam"], ["Action", "to wedge tight"], ["Music", "a jam session"], ["Abstract", "a difficulty; in a jam"]],
  PAN: [["Artifact", "the cooking vessel"], ["Language", "to pan a film; to criticise"], ["Art", "a camera pan"], ["Action", "to pan for gold"], ["Nature", "a salt pan"]],
  FILE: [["Artifact", "a folder of papers"], ["Tool", "the metal rasp"], ["Group", "a line of people; single file"], ["Game", "a column on a chessboard"], ["Law", "to file a claim"]],
  TRAIN: [["Vehicle", "the thing on rails"], ["Action", "to teach by repetition"], ["Textile", "the trailing part of a dress"], ["Abstract", "a train of thought"], ["Group", "a retinue"]],
  CASE: [["Artifact", "a container"], ["Law", "a legal matter"], ["Language", "the grammatical case; nominative, dative"], ["Science", "a patient"], ["Abstract", "an instance"]],
  CHECK: [["Action", "to verify"], ["Game", "in chess"], ["Money", "the bill, and the cheque"], ["Textile", "the pattern"], ["Language", "the tick mark"]],
  TIP: [["Shape", "the pointed end"], ["Money", "a gratuity"], ["Language", "a piece of advice"], ["Action", "to tilt over"], ["Place", "a rubbish tip"]],
  FOOT: [["Body", "the end of the leg"], ["Measure", "twelve inches"], ["Language", "a metrical foot in verse"], ["Place", "the foot of a hill or a bed"]],
  SPIRIT: [["Religion", "the soul, and a ghost"], ["Drink", "distilled alcohol"], ["Abstract", "morale; team spirit"], ["Science", "a volatile solvent"]],
  GUM: [["Food", "chewing gum"], ["Body", "the flesh around teeth"], ["Plant", "tree resin; a gum tree"], ["Substance", "adhesive"]],
  LOG: [["Plant", "a felled length of tree"], ["Language", "a written record"], ["Measure", "a logarithm"], ["Nautical", "a ship's log and log-line"]],
  SEAL: [["Animal", "the sea mammal"], ["Artifact", "a stamp pressed into wax"], ["Action", "to close something tight"], ["Tool", "a gasket or washer"]],
  KID: [["Person", "a child"], ["Animal", "a young goat"], ["Textile", "soft leather; kid gloves"], ["Action", "to joke; you're kidding"]],
  SOLE: [["Body", "the underside of the foot"], ["Textile", "the underside of a shoe"], ["Animal", "the flatfish"], ["Attribute", "only; the sole survivor"]],
  MINT: [["Plant", "the herb"], ["Money", "where coins are struck"], ["Attribute", "perfect; mint condition"], ["Food", "a boiled sweet"]],
  PLANT: [["Plant", "a growing thing"], ["Building", "a factory"], ["Action", "to put a seed in the ground"], ["Person", "an informer placed inside"]],
  MATCH: [["Artifact", "the small fire-stick"], ["Sport", "a contest"], ["Abstract", "an equal or a pair"], ["Person", "a marriage match"]],
  SUBJECT: [["Abstract", "the topic at hand"], ["Person", "a citizen of a monarch"], ["Language", "the subject of a sentence"], ["Science", "a person in an experiment"]],
  PRESENT: [["Object", "a gift"], ["Time", "now"], ["Action", "to introduce or hand over"], ["Attribute", "in attendance"]],
  SECOND: [["Time", "one sixtieth of a minute"], ["Measure", "the one after first"], ["Law", "to second a motion"], ["Person", "the assistant at a duel"]],
  POUND: [["Measure", "a unit of weight"], ["Money", "the currency"], ["Action", "to beat repeatedly"], ["Place", "where stray dogs are kept"]],
  CHAIR: [["Artifact", "the furniture"], ["Person", "who runs a meeting"], ["Abstract", "a professorship"], ["Law", "the electric chair"]],
  COMPANY: [["Trade", "a business"], ["Group", "guests; we have company"], ["Military", "a unit of soldiers"], ["Art", "a theatre or dance company"]],
  ORGAN: [["Body", "the heart, the liver"], ["Music", "the instrument with pipes"], ["Language", "a newspaper; the party organ"], ["Group", "a part of an institution"]],
  NOTE: [["Music", "a single sound"], ["Language", "a written message"], ["Money", "a banknote"], ["Action", "to notice"]],
  SPINE: [["Body", "the backbone"], ["Artifact", "the edge of a book"], ["Plant", "a thorn"], ["Abstract", "courage"]],
  NECK: [["Body", "between head and shoulders"], ["Artifact", "the neck of a bottle"], ["Music", "the neck of a guitar"], ["Nature", "an isthmus"]],
  HEEL: [["Body", "the back of the foot"], ["Textile", "the back of a shoe"], ["Food", "the end slice of a loaf"], ["Person", "a cad"]],
  LEG: [["Body", "what you stand on"], ["Artifact", "a table leg"], ["Sport", "one stage of a journey or a tie"], ["Game", "the leg side in cricket"]],
  PLOT: [["Language", "the story of a novel"], ["Place", "a parcel of land"], ["Abstract", "a conspiracy"], ["Measure", "to plot on a graph"]],
  SPELL: [["Religion", "words of magic"], ["Language", "to give the letters in order"], ["Time", "a period; a cold spell"], ["Trade", "a turn at work"]],
  POST: [["Artifact", "an upright timber"], ["Language", "the mail, and to publish"], ["Person", "a job or position"], ["Military", "a station one is posted to"]],
  LIGHT: [["Nature", "what the sun gives"], ["Measure", "not heavy"], ["Action", "to set alight"], ["Attribute", "pale in colour"]],
  FAIR: [["Abstract", "just"], ["Attribute", "light in colour"], ["Trade", "a market or funfair"], ["Nature", "fine weather"]],
  FINE: [["Attribute", "excellent"], ["Law", "a money penalty"], ["Measure", "thin or delicate"], ["Nature", "clear weather"]],
  MEAN: [["Measure", "the average"], ["Language", "to signify"], ["Attribute", "unkind"], ["Action", "to intend"]],
  SUIT: [["Textile", "the set of clothes"], ["Game", "the card suit"], ["Law", "a lawsuit"], ["Action", "to be fitting; it suits you"]],
  HEART: [["Body", "the organ"], ["Game", "the card suit"], ["Abstract", "courage; take heart"], ["Place", "the centre; the heart of the city"]],
  DIAMOND: [["Substance", "the gem"], ["Game", "the card suit"], ["Sport", "the baseball infield"], ["Shape", "the rhombus"]],
  POT: [["Artifact", "the cooking vessel"], ["Substance", "cannabis"], ["Game", "the stake in a card game"], ["Sport", "to pot a ball"]],
  PRESS: [["Action", "to push"], ["Language", "newspapers collectively"], ["Artifact", "the printing machine"], ["Sport", "a weightlifting press"]],
  LAP: [["Body", "the thighs when seated"], ["Sport", "one circuit of a track"], ["Action", "to drink as a cat does"], ["Shape", "an overlap"]],
  BUFF: [["Attribute", "the pale yellow colour"], ["Person", "an enthusiast"], ["Action", "to polish"], ["Textile", "buff leather"]],
  CONSOLE: [["Action", "to comfort"], ["Artifact", "a control panel"], ["Game", "a games console"], ["Building", "a bracket or console table"]],
  TURKEY: [["Place", "the country"], ["Animal", "the bird"], ["Abstract", "a flop; a bad film"], ["Sport", "three strikes in bowling"]],
  DUCK: [["Animal", "the water bird"], ["Action", "to dodge downward"], ["Sport", "a score of nought in cricket"], ["Textile", "a heavy cotton cloth"]],
  CRAB: [["Animal", "the shellfish"], ["Plant", "the crab apple"], ["Action", "to move sideways"], ["Person", "a bad-tempered one"]],
  BUCK: [["Animal", "a male deer"], ["Money", "a dollar"], ["Action", "to throw a rider"], ["Abstract", "responsibility; the buck stops here"]],
  FAN: [["Artifact", "what moves air"], ["Person", "an enthusiast"], ["Shape", "a fan shape"], ["Action", "to fan out"]],
  ROCK: [["Substance", "stone"], ["Music", "the music"], ["Action", "to sway"], ["Object", "a diamond"]],
  WAVE: [["Nature", "water rising and falling"], ["Action", "a greeting with the hand"], ["Science", "in physics; light and sound"], ["Body", "a wave in the hair"]],
  FLUKE: [["Abstract", "a stroke of luck"], ["Animal", "the tail of a whale, and a parasitic worm"], ["Nautical", "the barb of an anchor"]],
  DESERT: [["Nature", "arid land"], ["Action", "to abandon"], ["Abstract", "what one deserves; just deserts"]],
  PALM: [["Body", "the inside of the hand"], ["Plant", "the tree"], ["Action", "to conceal in the hand"]],
  IRIS: [["Body", "the coloured ring of the eye"], ["Plant", "the flower"], ["Artifact", "a camera aperture"]],
  TEMPLE: [["Building", "a place of worship"], ["Body", "the side of the forehead"], ["Artifact", "the arm of a pair of spectacles"]],
  CALF: [["Animal", "a young cow"], ["Body", "the muscle below the knee"], ["Nature", "an iceberg calving from a glacier"]],
  EAR: [["Body", "the organ of hearing"], ["Plant", "an ear of corn"], ["Music", "a good ear; an ear for music"]],
  SAGE: [["Plant", "the herb"], ["Person", "a wise elder"], ["Attribute", "the grey-green colour"]],
  CULTURE: [["Group", "the customs of a people"], ["Science", "bacteria grown in a dish"], ["Art", "the arts collectively"]],
  MASS: [["Science", "how much matter a thing has"], ["Religion", "the church service"], ["Measure", "a large quantity"]],
  SEASON: [["Time", "one of the four"], ["Food", "to add salt and spice"], ["Trade", "to age timber until it is ready"]],
  FAST: [["Measure", "quick"], ["Religion", "to go without food"], ["Attribute", "firmly fixed; hold fast"]],
  CONTRACT: [["Law", "a binding agreement"], ["Action", "to shrink"], ["Science", "to catch a disease"]],
  CURRENT: [["Nature", "the flow of water"], ["Science", "the flow of electricity"], ["Time", "present-day"]],
  GRAVE: [["Place", "a burial place"], ["Attribute", "serious"], ["Language", "the accent mark; grave and acute"]],
  STAPLE: [["Artifact", "the wire fastener"], ["Food", "a basic foodstuff"], ["Trade", "a principal product"]],
  CHEST: [["Body", "the ribcage"], ["Artifact", "a strong box"], ["Building", "a chest of drawers"]],
  TOOTH: [["Body", "what bites"], ["Artifact", "a tooth on a gear or comb"], ["Tool", "a saw tooth"]],
  ARTICLE: [["Language", "a piece of writing, and a, an, the"], ["Object", "a thing; an article of clothing"], ["Law", "a clause of a treaty"]],
  VOLUME: [["Language", "a book, one of several"], ["Music", "loudness"], ["Measure", "how much space a thing fills"]],
  MOUTH: [["Body", "where food goes in"], ["Nature", "where a river meets the sea"], ["Place", "the entrance to a cave"]],
  SINK: [["Artifact", "the basin"], ["Action", "to go under"], ["Science", "a heat sink"]],
  WELL: [["Nature", "a shaft sunk for water"], ["Attribute", "in good health"], ["Building", "a stairwell"]],
  STAMP: [["Language", "what franks a letter"], ["Action", "to bring the foot down"], ["Tool", "the die that makes a mark"]],
  YARD: [["Measure", "three feet"], ["Place", "an enclosed space"], ["Nautical", "the spar a sail hangs from"]],
  ROW: [["Shape", "a line of things"], ["Group", "a quarrel"], ["Action", "to propel a boat with oars"]],
  LIE: [["Language", "an untruth"], ["Action", "to be horizontal"], ["Sport", "where the golf ball sits"]],
  MOMENT: [["Time", "a short while"], ["Science", "turning force about a point"], ["Abstract", "importance; of great moment"]],
  NAIL: [["Body", "what grows on a finger"], ["Artifact", "the metal fastener"], ["Action", "to succeed; nailed it"]],
  ARMS: [["Body", "the two limbs"], ["Military", "weapons"], ["Abstract", "a coat of arms"]],
  JERSEY: [["Place", "the Channel island"], ["Textile", "a knitted shirt"], ["Animal", "the breed of cow"]],
  BAT: [["Animal", "the flying mammal"], ["Sport", "what a batsman holds"], ["Action", "to bat an eyelid"]],
  MINUTE: [["Time", "sixty seconds"], ["Measure", "tiny; a minute quantity"], ["Language", "the written record of a meeting"]],
  OBJECT: [["Object", "a thing"], ["Action", "to protest"], ["Language", "the object of a verb"]],
  SENTENCE: [["Language", "a complete thought in words"], ["Law", "the punishment a judge gives"]],
  QUARRY: [["Place", "where stone is cut"], ["Animal", "the hunted creature"]],
  CABINET: [["Artifact", "a cupboard"], ["Group", "the ministers of a government"]],
  SOLUTION: [["Abstract", "the answer to a problem"], ["Science", "a liquid with something dissolved in it"]],
  PUPIL: [["Person", "a student"], ["Body", "the opening in the eye"]],
  CRANE: [["Animal", "the long-legged bird"], ["Artifact", "the lifting machine"], ["Action", "to crane one's neck"]],
  CHINA: [["Place", "the country"], ["Substance", "porcelain"]],
  STERN: [["Nautical", "the back of a ship"], ["Attribute", "severe"]],
  REFRAIN: [["Action", "to hold back from doing"], ["Music", "the repeated chorus"]],
  STABLE: [["Building", "where horses are kept"], ["Attribute", "steady, not liable to fall"]],
  NOVEL: [["Language", "a long work of fiction"], ["Attribute", "new and unusual"]],
  PATIENT: [["Science", "one under a doctor's care"], ["Attribute", "able to wait without complaint"]],
  SPADE: [["Tool", "the digging implement"], ["Game", "the card suit"]],
  SEWER: [["Building", "the drain under a city"], ["Person", "one who sews"]],
  BASS: [["Music", "the low register"], ["Animal", "the fish"]],
  SOW: [["Animal", "a female pig"], ["Action", "to scatter seed"]],
  WIND: [["Nature", "moving air"], ["Action", "to turn a handle or a clock"]],
  TEAR: [["Body", "what falls from the eye"], ["Action", "to rip"]]
};
