// The general word list: the stock Crosslink builds boards from beyond the
// polysemous registry. e = ease (3 a word you can picture at once, 1 a word
// that needs a fact to place). Written by hand; facts kept round and checkable.
window.CROSSLINK = window.CROSSLINK || {};
window.CROSSLINK.words = {
  ACTOR: { e: 2, k: "people", d: "One who is someone else for a living." },
  AFRICA: { e: 3, k: "continent", d: "The second largest, with 54 countries and the youngest population on earth." },
  AIRPORT: { e: 3, k: "travel", d: "Where aircraft are kept, met and delayed." },
  AMERICA: { e: 3, k: "continent", d: "Two continents joined at Panama; also, on its own, the United States." },
  AMSTERDAM: { e: 2, k: "city", d: "The Netherlands' capital, and its canals." },
  ANCHOR: { e: 3, k: "travel", d: "The iron weight that holds a ship where it is; also the one steady thing." },
  ANT: { e: 3, k: "animal", d: "The insect that solved organisation before we did." },
  ANTARCTICA: { e: 3, k: "continent", d: "The frozen continent. No permanent residents, only visiting scientists." },
  APPLE: { e: 3, k: "food", d: "The orchard fruit that carries the most stories." },
  ARGENTINA: { e: 3, k: "country", d: "Southern South America. Capital Buenos Aires. About 46 million people." },
  ARMSTRONG: { e: 2, k: "figure", d: "Two of them: Neil, first to walk on the moon, and Louis, who invented much of jazz." },
  ARMY: { e: 2, k: "people", d: "People enough to take a country." },
  ASH: { e: 3, k: "nature", d: "What fire leaves when it has finished." },
  ASIA: { e: 3, k: "continent", d: "The largest continent, and the most populous: some 4.7 billion people." },
  ATHENS: { e: 3, k: "city", d: "Greece's capital, under the Parthenon; the oldest capital in Europe." },
  ATOM: { e: 1, k: "idea", d: "The smallest piece of an element." },
  AUSTRALIA: { e: 3, k: "country", d: "A country and a continent at once. Capital Canberra. About 27 million people." },
  AUSTRIA: { e: 3, k: "country", d: "Central Europe, mostly mountain. Capital Vienna. About 9 million people." },
  BACH: { e: 2, k: "figure", d: "German composer, 1685-1750. The foundation most western music is built on." },
  BAG: { e: 3, k: "thing", d: "A soft container with a handle." },
  BAKER: { e: 2, k: "people", d: "One who makes bread, by the dozen." },
  BALLOON: { e: 3, k: "travel", d: "A bag of lighter gas, and the first thing to carry people up." },
  BANGKOK: { e: 2, k: "city", d: "Thailand's capital, and its river." },
  BARK: { e: 3, k: "nature", d: "The skin of a tree. Also the noise a dog makes, and a small sailing ship." },
  BARREL: { e: 3, k: "food", d: "A wooden cask; also the tube of a gun." },
  BASKET: { e: 3, k: "thing", d: "Woven, open, and carried." },
  BATTERY: { e: 3, k: "thing", d: "What keeps charge until it is wanted; also assault, and a set of guns." },
  BEACH: { e: 3, k: "nature", d: "The sand or shingle at that meeting." },
  BEACON: { e: 3, k: "travel", d: "A fire or light lit to warn or to guide." },
  BEE: { e: 3, k: "animal", d: "The insect that makes honey and pollinates the rest of dinner." },
  BEER: { e: 3, k: "food", d: "Fermented grain, and the oldest reason to keep a barrel." },
  BEETHOVEN: { e: 2, k: "figure", d: "German composer, 1770-1827. Nine symphonies, the last written deaf." },
  BEIJING: { e: 3, k: "city", d: "China's capital, around the Forbidden City." },
  BELGIUM: { e: 3, k: "country", d: "Western Europe. Capital Brussels, which also seats the European Union. About 12 million people." },
  BELL: { e: 2, k: "figure", d: "Scottish-American inventor, 1847-1922. The telephone." },
  BELT: { e: 3, k: "thing", d: "What holds trousers up; also a region, and a blow." },
  BERLIN: { e: 3, k: "city", d: "Germany's capital, cut in two by a wall from 1961 to 1989." },
  "BERNERS-LEE": { e: 1, k: "figure", d: "English computer scientist, born 1955. Invented the World Wide Web at CERN in 1989 and gave it away unpatented." },
  BICYCLE: { e: 3, k: "travel", d: "Two wheels and a chain; the most efficient machine ever built." },
  BIRD: { e: 3, k: "animal", d: "A feathered animal with wings, most of which fly." },
  BLOOD: { e: 3, k: "body", d: "What the heart moves, and what family shares." },
  BLOSSOM: { e: 3, k: "nature", d: "The flower of a fruit tree, and the one week of the year worth travelling to see it." },
  BOAT: { e: 3, k: "travel", d: "A small vessel on water." },
  BOILER: { e: 3, k: "thing", d: "A closed iron vessel in which water is turned to steam and kept until it is wanted." },
  BONE: { e: 3, k: "body", d: "The frame under everything." },
  BOOK: { e: 3, k: "thing", d: "Pages bound together, and the reason any of this lasted." },
  BOTTLE: { e: 3, k: "thing", d: "Glass for liquid, with a narrow neck; also nerve, in slang." },
  BOWL: { e: 3, k: "food", d: "A deep dish; also a stadium, and to send a ball down a pitch." },
  BOX: { e: 3, k: "thing", d: "A container with corners, and to fight with fists." },
  BRAIN: { e: 3, k: "body", d: "The organ of thought; also the clever one in the group." },
  BRANCH: { e: 3, k: "nature", d: "An arm of a tree; also an office of a bank away from the main one." },
  BRAZIL: { e: 3, k: "country", d: "The largest country in South America. Capital Brasilia. About 212 million people." },
  BREAD: { e: 3, k: "food", d: "Flour, water and time; the oldest cooked food." },
  BREAKFAST: { e: 3, k: "food", d: "The meal that breaks the night's fast." },
  BREATH: { e: 3, k: "body", d: "One turn of the lungs, and the pause before speaking." },
  BRITAIN: { e: 3, k: "country", d: "The island holding England, Scotland and Wales. Capital London. The United Kingdom has about 69 million people." },
  BROOM: { e: 3, k: "thing", d: "The brush on a long handle." },
  BRUSH: { e: 2, k: "art", d: "What paint is put on with; also a brief encounter, and undergrowth." },
  BUCKET: { e: 3, k: "thing", d: "What water is carried in." },
  BUS: { e: 3, k: "travel", d: "The public one." },
  BUTCHER: { e: 2, k: "people", d: "One who cuts meat." },
  BUTTER: { e: 3, k: "food", d: "Cream churned until it changes its mind." },
  BUTTON: { e: 3, k: "thing", d: "What fastens a coat, and what starts a machine." },
  CAESAR: { e: 2, k: "figure", d: "Roman general and dictator, 100-44 BC. Crossed the Rubicon; gave his name to a month." },
  CAIRO: { e: 3, k: "city", d: "Egypt's capital, on the Nile, and the largest city in the Arab world." },
  CAKE: { e: 3, k: "food", d: "Flour and sugar, made for an occasion." },
  CAMEL: { e: 3, k: "animal", d: "The desert animal that carries its own water." },
  CAMERA: { e: 3, k: "thing", d: "The box that keeps what the light did." },
  CANADA: { e: 3, k: "country", d: "North America, second largest country by area. Capital Ottawa. About 41 million people." },
  CANDLE: { e: 3, k: "thing", d: "Wax with a wick, and the oldest portable light." },
  CANVAS: { e: 2, k: "art", d: "What a painting is on, and what a tent is made of." },
  CAR: { e: 3, k: "travel", d: "The private engine, four wheels, and most of a century." },
  CARGO: { e: 3, k: "travel", d: "What a ship is carrying, and the reason it sailed." },
  CAT: { e: 3, k: "animal", d: "The animal that agreed to live near us." },
  CAVE: { e: 3, k: "nature", d: "A hollow in rock big enough to go into." },
  CERVANTES: { e: 2, k: "figure", d: "Spanish novelist, 1547-1616. Don Quixote, often called the first modern novel." },
  CHAIN: { e: 3, k: "thing", d: "Links that will not come apart, and any sequence of that kind." },
  CHAPLIN: { e: 2, k: "figure", d: "English film-maker, 1889-1977. The Tramp, and the last great silent comedies." },
  CHEESE: { e: 3, k: "food", d: "Milk kept on purpose." },
  CHICAGO: { e: 2, k: "city", d: "On Lake Michigan, where the skyscraper was invented." },
  CHILE: { e: 3, k: "country", d: "A ribbon of land down the Pacific coast. Capital Santiago. About 20 million people." },
  CHIMNEY: { e: 3, k: "thing", d: "The way out for smoke." },
  CHINA: { e: 3, k: "country", d: "East Asia. Capital Beijing. About 1.4 billion people; also the porcelain, named after it." },
  CHOIR: { e: 2, k: "people", d: "Voices arranged." },
  CHOPIN: { e: 2, k: "figure", d: "Polish composer, 1810-1849. Wrote almost entirely for the piano." },
  CHORUS: { e: 2, k: "art", d: "The part of a song that comes back, and the crowd that sings it." },
  CHURCHILL: { e: 2, k: "figure", d: "British prime minister, 1874-1965. Led Britain through the Second World War." },
  CINEMA: { e: 2, k: "art", d: "The building for films, and the art itself." },
  CITY: { e: 3, k: "people", d: "A town that kept growing after it had any reason to." },
  CLEOPATRA: { e: 2, k: "figure", d: "Last pharaoh of Egypt, 69-30 BC. Ruled through the Roman civil wars." },
  CLIFF: { e: 3, k: "nature", d: "Ground that stops without warning." },
  CLOCK: { e: 3, k: "thing", d: "The machine that measures the day out." },
  CLOTH: { e: 3, k: "thing", d: "Woven fibre, before anyone has cut it." },
  CLOUD: { e: 3, k: "nature", d: "Water held in the air until it can no longer be held." },
  CLOWN: { e: 2, k: "people", d: "One paid to be laughed at." },
  COAL: { e: 3, k: "nature", d: "Black rock that burns; a forest, several million years on." },
  COAT: { e: 3, k: "thing", d: "The outer garment, and a layer of paint." },
  COFFEE: { e: 3, k: "food", d: "The roasted bean, and the drink that got the enlightenment out of bed." },
  COLOMBIA: { e: 2, k: "country", d: "Northern South America, on two oceans. Capital Bogota. About 52 million people." },
  COLUMBUS: { e: 2, k: "figure", d: "Genoese navigator, 1451-1506. Crossed the Atlantic in 1492 believing it was Asia." },
  COLUMN: { e: 3, k: "thing", d: "A pillar holding a roof up; and a strip of print running down a page. The newspaper borrowed the word from the architect." },
  COMET: { e: 3, k: "nature", d: "A dirty snowball on a long orbit, with a tail." },
  COMPASS: { e: 3, k: "travel", d: "The needle that finds north; also the pair of legs that draws a circle." },
  COMPUTER: { e: 3, k: "thing", d: "The machine that does arithmetic until it looks like thought." },
  COOK: { e: 2, k: "figure", d: "English navigator, 1728-1779. Charted the Pacific, including New Zealand and eastern Australia." },
  COPENHAGEN: { e: 2, k: "city", d: "Denmark's capital, and a great many bicycles." },
  COPPER: { e: 3, k: "nature", d: "The red metal, and the first wire." },
  COPY: { e: 2, k: "art", d: "Text waiting to be set — what a writer hands over and an editor hands back." },
  COTTON: { e: 3, k: "nature", d: "The white fibre round a seed, and the whole industry that grew out of spinning it." },
  COW: { e: 3, k: "animal", d: "Kept for milk and beef; the reason for most fences." },
  CROW: { e: 3, k: "animal", d: "A black bird of unusual intelligence." },
  CROWD: { e: 2, k: "people", d: "People enough to lose one." },
  CRUST: { e: 3, k: "food", d: "The hard outside of a loaf. Also the thin cold skin of a planet." },
  CUBA: { e: 3, k: "country", d: "The largest island in the Caribbean. Capital Havana. About 11 million people." },
  CURIE: { e: 2, k: "figure", d: "Physicist and chemist, 1867-1934. Radioactivity, and two Nobel prizes in two sciences." },
  DANCER: { e: 2, k: "people", d: "One who moves for a living." },
  DANTE: { e: 2, k: "figure", d: "Italian poet, 1265-1321. Walked through hell and wrote it down." },
  DARWIN: { e: 2, k: "figure", d: "English naturalist, 1809-1882. Evolution by natural selection." },
  DAY: { e: 1, k: "idea", d: "One turn of the earth, and the light half of it." },
  DEADLINE: { e: 2, k: "idea", d: "The hour after which it is too late. Named for a line at a prison camp that prisoners were shot for crossing." },
  DEBT: { e: 1, k: "idea", d: "Money owed, and any obligation." },
  DECK: { e: 3, k: "travel", d: "The floor of a ship, and a pack of cards." },
  DEER: { e: 3, k: "animal", d: "The forest animal with antlers, hunted since there were hunters." },
  DELHI: { e: 3, k: "city", d: "India's capital region; New Delhi sits inside it." },
  DENMARK: { e: 3, k: "country", d: "Scandinavia, flat and coastal. Capital Copenhagen. About 6 million people." },
  DESERT: { e: 3, k: "nature", d: "Land that has given up on rain." },
  DEW: { e: 3, k: "nature", d: "Water the morning leaves on grass." },
  DIAMOND: { e: 3, k: "nature", d: "Carbon under enormous pressure; also a card suit and a baseball field." },
  DICKENS: { e: 2, k: "figure", d: "English novelist, 1812-1870. Serialised, and read aloud to crowds." },
  DOCTOR: { e: 2, k: "people", d: "One who treats the sick; also the highest degree." },
  DOG: { e: 3, k: "animal", d: "The animal that agreed to live with us first." },
  DOLPHIN: { e: 3, k: "animal", d: "A small whale with a reputation for cleverness." },
  DOOR: { e: 3, k: "thing", d: "The way in, and the way out." },
  DOUGH: { e: 3, k: "food", d: "Flour and water worked together and left to rise. Also, in slang, money." },
  DRAGON: { e: 2, k: "people", d: "The great winged serpent; in the east, lucky." },
  DREAM: { e: 1, k: "idea", d: "What the sleeping mind makes, and what the waking one wants." },
  DRUM: { e: 2, k: "art", d: "What is hit for rhythm; also a cylinder, and to drum up support." },
  DUBLIN: { e: 3, k: "city", d: "Ireland's capital, on the Liffey." },
  DUCK: { e: 3, k: "animal", d: "A water bird; also to lower your head quickly, and a score of nothing." },
  DUST: { e: 3, k: "nature", d: "The finest dry powder, which settles on everything left alone." },
  EAGLE: { e: 3, k: "animal", d: "A large bird of prey, and the flag of half the world's armies." },
  ECLIPSE: { e: 3, k: "nature", d: "One body stepping in front of another's light." },
  EDINBURGH: { e: 3, k: "city", d: "Scotland's capital, with a castle on an old volcano." },
  EDISON: { e: 2, k: "figure", d: "American inventor, 1847-1931. The phonograph, and the first practical light bulb." },
  EDITOR: { e: 2, k: "people", d: "The one who decides what goes in, what comes out, and what it is called." },
  EGG: { e: 3, k: "food", d: "What a bird lays, and the start of nearly everything else." },
  EGYPT: { e: 3, k: "country", d: "North-east Africa, along the Nile. Capital Cairo. About 114 million people." },
  EINSTEIN: { e: 2, k: "figure", d: "Physicist, 1879-1955. Relativity, and the most famous equation there is." },
  ELEPHANT: { e: 3, k: "animal", d: "The largest land animal, with a nose that works as a hand." },
  EMPIRE: { e: 1, k: "idea", d: "Territories held under one authority." },
  ENGINE: { e: 3, k: "thing", d: "What turns fuel into motion." },
  ENGINEER: { e: 3, k: "travel", d: "One who makes machines work, and keeps them working." },
  ENVELOPE: { e: 3, k: "thing", d: "The paper a letter travels in; also the limit of what a thing can do." },
  ETHIOPIA: { e: 2, k: "country", d: "East Africa, never colonised. Capital Addis Ababa. About 130 million people." },
  EUROPE: { e: 3, k: "continent", d: "The smallest continent by land but not by consequence. About 45 countries." },
  FACE: { e: 3, k: "body", d: "The front of the head, and the part of anything turned outward." },
  FARADAY: { e: 2, k: "figure", d: "English scientist, 1791-1867. Electromagnetic induction: the motor and the generator." },
  FARMER: { e: 2, k: "people", d: "One who works the land." },
  FEAR: { e: 1, k: "idea", d: "Expecting the worse one, usually with some." },
  FEAST: { e: 3, k: "food", d: "A meal too large for an ordinary day." },
  FEATHER: { e: 3, k: "animal", d: "What a bird is covered in, and what a pen once was." },
  FINGER: { e: 3, k: "body", d: "One of five, and to point one at someone." },
  FINLAND: { e: 3, k: "country", d: "Northern Europe, and a great many lakes. Capital Helsinki. About 5.6 million people." },
  FIRE: { e: 3, k: "nature", d: "Burning, and the light and heat it throws." },
  FLAG: { e: 3, k: "thing", d: "Cloth flown to say whose it is." },
  FLAME: { e: 3, k: "nature", d: "Fire with a shape." },
  FLEMING: { e: 2, k: "figure", d: "Scottish bacteriologist, 1881-1955. Noticed the mould that became penicillin." },
  FLOOR: { e: 3, k: "thing", d: "What you stand on, and the right to speak in a chamber." },
  FLORENCE: { e: 3, k: "city", d: "Italy, where the Renaissance was paid for." },
  FLOUR: { e: 3, k: "food", d: "Grain ground down, waiting to be bread." },
  FLOWER: { e: 3, k: "nature", d: "The part of a plant made to be noticed." },
  FLUTE: { e: 2, k: "art", d: "The instrument that is only air and holes." },
  FOG: { e: 3, k: "nature", d: "Cloud that has come down to eye level." },
  FORD: { e: 2, k: "figure", d: "American manufacturer, 1863-1947. The moving assembly line, and a car most people could buy." },
  FOREST: { e: 3, k: "nature", d: "Trees enough to lose yourself in." },
  FORK: { e: 3, k: "food", d: "Two or more prongs on a handle; also where a road divides." },
  FORMULA: { e: 1, k: "idea", d: "A rule written in symbols, and a fixed way of doing anything." },
  FOX: { e: 3, k: "animal", d: "The wild dog with a better reputation for cunning." },
  FRANCE: { e: 3, k: "country", d: "Western Europe. Capital Paris. About 68 million people." },
  FRANKLIN: { e: 2, k: "figure", d: "American printer, 1706-1790. Also postmaster, diplomat and signer of the Declaration; and he chose PRINTER for his own gravestone." },
  FROG: { e: 3, k: "animal", d: "The amphibian that starts as a tadpole." },
  FROST: { e: 3, k: "nature", d: "Ice drawn on things overnight." },
  FURNACE: { e: 3, k: "thing", d: "A fire built inside walls, so that the heat has nowhere to go but where it is sent." },
  GAGARIN: { e: 2, k: "figure", d: "Soviet cosmonaut, 1934-1968. The first human being in space, in 1961." },
  GALE: { e: 3, k: "nature", d: "A wind strong enough to be given a name." },
  GALILEO: { e: 2, k: "figure", d: "Italian astronomer, 1564-1642. Turned the new telescope on the sky and was tried for it." },
  GANDHI: { e: 2, k: "figure", d: "Indian leader, 1869-1948. Non-violent resistance, and Indian independence." },
  GARDEN: { e: 3, k: "thing", d: "Ground kept deliberately." },
  GARDENER: { e: 2, k: "people", d: "One who keeps a garden, which is to say one who is never finished." },
  GARLIC: { e: 3, k: "food", d: "The bulb that keeps its friends and its enemies." },
  GATE: { e: 3, k: "thing", d: "A door in a fence, and the boarding point at an airport." },
  GEAR: { e: 3, k: "thing", d: "Toothed wheels turning each other, and the kit for a job." },
  GENEVA: { e: 2, k: "city", d: "Switzerland, on its lake, and the seat of a great many treaties." },
  GERMANY: { e: 3, k: "country", d: "Central Europe. Capital Berlin. About 84 million people; the largest economy in Europe." },
  GHOST: { e: 2, k: "people", d: "What is said to remain, and to write a book under another name." },
  GIANT: { e: 2, k: "people", d: "Very large, in stories and in industries." },
  GIRAFFE: { e: 3, k: "animal", d: "The tallest animal, built entirely around reaching." },
  GLACIER: { e: 3, k: "nature", d: "A river of ice, moving too slowly to watch." },
  GLASS: { e: 3, k: "thing", d: "The clear hard material, and a vessel made of it." },
  GLOVE: { e: 3, k: "thing", d: "What the hand wears, and what is thrown down to challenge." },
  GOAT: { e: 3, k: "animal", d: "Kept for milk, and for eating what nothing else will." },
  GOLD: { e: 3, k: "nature", d: "The metal nobody has ever tired of." },
  GOOSE: { e: 3, k: "animal", d: "A larger water bird with a longer memory." },
  GRAPE: { e: 3, k: "food", d: "The fruit that becomes wine if left alone." },
  GRASS: { e: 3, k: "nature", d: "The green that covers ground when nothing taller does." },
  GRAVITY: { e: 1, k: "idea", d: "Why things fall, and why the moon does not." },
  GREECE: { e: 3, k: "country", d: "South-east Europe. Capital Athens. About 10 million people, and the source of most of the words." },
  GUITAR: { e: 2, k: "art", d: "Six strings, and most of the last century's music." },
  GUTENBERG: { e: 2, k: "figure", d: "German printer, about 1400-1468. Movable type in Europe, and everything that followed." },
  HAIR: { e: 3, k: "body", d: "What grows on the head, and the thinnest possible margin." },
  HAMMER: { e: 3, k: "thing", d: "The tool for driving nails, and for settling arguments in an auction." },
  HARBOUR: { e: 3, k: "travel", d: "Water sheltered enough to leave a ship in; also to hold a thought." },
  HARP: { e: 2, k: "art", d: "Strings plucked in a frame, and the oldest of them." },
  HAT: { e: 3, k: "thing", d: "What the head wears, and the role a person takes on." },
  HAVANA: { e: 3, k: "city", d: "Cuba's capital, and its harbour." },
  HEADLINE: { e: 3, k: "art", d: "The line set in the biggest letter on the page, and often the only one read." },
  HEAT: { e: 3, k: "nature", d: "Warmth, and a lot of it. Also a qualifying race, and pressure put on a person." },
  HEN: { e: 3, k: "animal", d: "The female chicken, and where eggs come from." },
  HERO: { e: 2, k: "people", d: "The one the story follows, and the one who does the hard thing." },
  HILL: { e: 3, k: "nature", d: "A rise of ground, short of a mountain." },
  HITCHCOCK: { e: 2, k: "figure", d: "English director, 1899-1980. Suspense, and the shower scene." },
  HIVE: { e: 3, k: "animal", d: "What bees build, and any place of that much activity." },
  HOMER: { e: 2, k: "figure", d: "Greek poet, around the eighth century BC. The Iliad and the Odyssey." },
  HONEY: { e: 3, k: "animal", d: "What the hive is for." },
  HOPE: { e: 1, k: "idea", d: "Expecting the better outcome without evidence." },
  HORIZON: { e: 3, k: "nature", d: "The line you never reach." },
  HORSE: { e: 3, k: "animal", d: "The animal that carried everything until the engine." },
  HOUR: { e: 1, k: "idea", d: "Sixty minutes, and a length of anyone's attention." },
  ICE: { e: 3, k: "nature", d: "Water gone solid, and slippery about it." },
  ICELAND: { e: 3, k: "country", d: "North Atlantic, volcanic. Capital Reykjavik. About 390 thousand people." },
  INCOME: { e: 1, k: "idea", d: "Money coming in, over a stretch of time." },
  INDIA: { e: 3, k: "country", d: "South Asia. Capital New Delhi. About 1.45 billion people, the most of any country." },
  INDONESIA: { e: 3, k: "country", d: "Thousands of islands across the equator. Capital Jakarta. About 280 million people." },
  INK: { e: 3, k: "thing", d: "The dark liquid that made writing portable." },
  IRAN: { e: 2, k: "country", d: "Western Asia, Persia until 1935. Capital Tehran. About 90 million people." },
  IRELAND: { e: 3, k: "country", d: "Western Europe. Capital Dublin. About 5.4 million people in the republic." },
  IRON: { e: 3, k: "nature", d: "The metal that built the modern world, and rusts to prove it." },
  ISLAND: { e: 3, k: "nature", d: "Land with water all round it." },
  ISTANBUL: { e: 3, k: "city", d: "Turkey's largest city, on two continents. Byzantium, then Constantinople, then this." },
  ITALY: { e: 3, k: "country", d: "Southern Europe, shaped like a boot. Capital Rome. About 59 million people." },
  JAPAN: { e: 3, k: "country", d: "East Asia, four main islands. Capital Tokyo. About 124 million people." },
  JERUSALEM: { e: 3, k: "city", d: "An ancient city, holy to Judaism, Christianity and Islam alike." },
  JOBS: { e: 2, k: "figure", d: "American businessman, 1955-2011. Co-founded Apple; also, the plural of work." },
  JUDGE: { e: 2, k: "people", d: "One who decides in court, and to form an opinion." },
  KANGAROO: { e: 3, k: "animal", d: "The Australian animal with a pocket." },
  KENYA: { e: 3, k: "country", d: "East Africa, across the equator. Capital Nairobi. About 55 million people." },
  KETTLE: { e: 3, k: "food", d: "The pot that boils water, and furs up with scale." },
  KING: { e: 2, k: "people", d: "The man who rules, and the tallest piece in chess." },
  KNEE: { e: 3, k: "body", d: "The hinge in the middle of the leg." },
  KNIFE: { e: 3, k: "food", d: "A blade with a handle; the first tool and still the sharpest." },
  KNIGHT: { e: 2, k: "people", d: "The armoured horseman; in chess, the piece that jumps." },
  KNOT: { e: 3, k: "travel", d: "Rope tied so it will not slip; also one nautical mile an hour." },
  KOREA: { e: 3, k: "country", d: "A peninsula in East Asia, divided since 1948. Seoul is the southern capital." },
  KYOTO: { e: 2, k: "city", d: "Japan's capital for a thousand years, before Tokyo." },
  LADDER: { e: 3, k: "thing", d: "The way up when there are no stairs; also a run in a stocking." },
  LAKE: { e: 3, k: "nature", d: "Water with land all round it." },
  LAMP: { e: 3, k: "thing", d: "A holder for a light." },
  LANGUAGE: { e: 1, k: "idea", d: "The system a people think out loud in." },
  LAW: { e: 1, k: "idea", d: "The rule that is enforced, and the pattern that always holds." },
  LEAF: { e: 3, k: "nature", d: "The flat green part of a plant, and a page of a book." },
  LEMON: { e: 3, k: "food", d: "The sour citrus; also anything that turns out badly." },
  LEONARDO: { e: 2, k: "figure", d: "Italian artist and engineer, 1452-1519. The Mona Lisa, and notebooks nobody read in time." },
  LEVER: { e: 3, k: "thing", d: "A bar and a fulcrum: the whole of mechanics in two parts." },
  LIBEL: { e: 1, k: "idea", d: "Something published that is untrue and damaging. It is only libel once someone else has read it." },
  LIBRARY: { e: 2, k: "art", d: "Where books are kept for reading." },
  LIGHTNING: { e: 3, k: "nature", d: "Electricity taking the shortest way to the ground." },
  LIMA: { e: 2, k: "city", d: "Peru's capital, on the Pacific." },
  LINCOLN: { e: 2, k: "figure", d: "American president, 1809-1865. Held the union together and ended slavery in it." },
  LION: { e: 3, k: "animal", d: "The big cat that hunts in company." },
  LISBON: { e: 3, k: "city", d: "Portugal's capital, on the Tagus, rebuilt after the earthquake of 1755." },
  LOAF: { e: 3, k: "food", d: "Bread in one piece, as it left the oven. Also, as a verb, to do nothing in particular." },
  LOBSTER: { e: 3, k: "animal", d: "A shellfish with claws, boiled red." },
  LOCK: { e: 3, k: "thing", d: "What a key opens; also a section of canal that lifts boats." },
  LONDON: { e: 3, k: "city", d: "Britain's capital, on the Thames. Roman in origin, and named Londinium then." },
  LOOM: { e: 3, k: "thing", d: "The frame that holds one set of threads still while another is passed through them." },
  LOVELACE: { e: 2, k: "figure", d: "English mathematician, 1815-1852. Wrote the first algorithm meant for a machine." },
  LUCK: { e: 1, k: "idea", d: "The part nobody arranged." },
  LUNG: { e: 3, k: "body", d: "What breathes." },
  MACHINE: { e: 3, k: "thing", d: "Anything built to do work repeatedly." },
  MADRID: { e: 3, k: "city", d: "Spain's capital, high on the plateau in the middle of the country." },
  MAGELLAN: { e: 2, k: "figure", d: "Portuguese navigator, 1480-1521. His expedition first went round the world; he did not survive it." },
  MAGNET: { e: 3, k: "thing", d: "Iron that has made up its mind about north." },
  MANDELA: { e: 2, k: "figure", d: "South African leader, 1918-2013. Twenty-seven years in prison, then president." },
  MAP: { e: 3, k: "travel", d: "The world made small and flat enough to fold." },
  MARCONI: { e: 2, k: "figure", d: "Italian inventor, 1874-1937. Sent the first radio signal across the Atlantic." },
  MARGIN: { e: 2, k: "thing", d: "The white border a page keeps round its words; and the room left over in anything else." },
  MARKET: { e: 1, k: "idea", d: "Where trade happens, and everyone who might buy." },
  MAST: { e: 3, k: "travel", d: "The pole a sail hangs from." },
  MEMORY: { e: 1, k: "idea", d: "What is kept of what happened, and where a computer keeps it." },
  METEOR: { e: 3, k: "nature", d: "A stone from space, burning as it arrives." },
  MEXICO: { e: 3, k: "country", d: "North America. Capital Mexico City. About 130 million people." },
  MICHELANGELO: { e: 2, k: "figure", d: "Italian artist, 1475-1564. The Sistine ceiling, and the David." },
  MICROSCOPE: { e: 3, k: "thing", d: "The tube that makes small things large." },
  MILK: { e: 3, k: "food", d: "What mammals feed their young; also to extract steadily." },
  MILL: { e: 3, k: "thing", d: "A building where one machine is repeated until the building is the machine." },
  MINER: { e: 2, k: "people", d: "One who works underground." },
  MIRROR: { e: 3, k: "thing", d: "Glass that gives you back." },
  MONET: { e: 2, k: "figure", d: "French painter, 1840-1926. Impressionism took its name from one of his canvases." },
  MONEY: { e: 1, k: "idea", d: "The agreement that makes exchange easy." },
  MONK: { e: 2, k: "people", d: "A man under religious vows; also the cell he lives in." },
  MONKEY: { e: 3, k: "animal", d: "A small primate, tailed and quick." },
  MOON: { e: 3, k: "nature", d: "The earth's one satellite, and the light it lends the night." },
  MOROCCO: { e: 3, k: "country", d: "North-west Africa. Capital Rabat. About 38 million people." },
  MORSE: { e: 2, k: "figure", d: "American inventor, 1791-1872. The telegraph, and the code that went down it." },
  MOSCOW: { e: 3, k: "city", d: "Russia's capital, around the Kremlin." },
  MOSS: { e: 3, k: "nature", d: "The low green growth on damp stone and bark. It has no roots to speak of." },
  MOTH: { e: 3, k: "animal", d: "The butterfly's night shift; ruinous to wool." },
  MOTOR: { e: 3, k: "thing", d: "An engine, usually electric." },
  MOUSE: { e: 3, k: "animal", d: "A small grey rodent; also the thing that moves the pointer." },
  MOZART: { e: 2, k: "figure", d: "Austrian composer, 1756-1791. Six hundred works in thirty-five years." },
  MUD: { e: 3, k: "nature", d: "Earth that has taken on more water than it can hold." },
  MUMBAI: { e: 3, k: "city", d: "India's largest city, and the home of its film industry. Bombay until 1995." },
  MUNICH: { e: 2, k: "city", d: "Germany, capital of Bavaria." },
  MUSEUM: { e: 2, k: "art", d: "Where objects are kept for looking at." },
  MUSK: { e: 2, k: "figure", d: "American entrepreneur, born 1971. Tesla and SpaceX; also a scent, from the deer." },
  NAPLES: { e: 2, k: "city", d: "Italy, under Vesuvius, and the birthplace of pizza." },
  NEEDLE: { e: 3, k: "thing", d: "What thread goes through, and what points north on a compass." },
  NEST: { e: 3, k: "animal", d: "What a bird builds to keep eggs in." },
  NETHERLANDS: { e: 3, k: "country", d: "Western Europe, much of it below sea level. Capital Amsterdam. About 18 million people." },
  NEWS: { e: 2, k: "idea", d: "What happened recently and is worth telling. Worth much less by the afternoon." },
  NEWTON: { e: 2, k: "figure", d: "English physicist, 1642-1727. Gravity, the laws of motion, and half of calculus." },
  NIGERIA: { e: 3, k: "country", d: "West Africa, and the most populous country in Africa. Capital Abuja. About 230 million people." },
  NIGHT: { e: 1, k: "idea", d: "The other half." },
  NILE: { e: 3, k: "nature", d: "The river Egypt is built along, and the longest in Africa." },
  NOBEL: { e: 2, k: "figure", d: "Swedish chemist, 1833-1896. Invented dynamite, then left his fortune to the prizes." },
  NORWAY: { e: 3, k: "country", d: "Scandinavia, all fjord and coast. Capital Oslo. About 5.5 million people." },
  NOSE: { e: 3, k: "body", d: "What you smell with, and the front of an aircraft." },
  NURSE: { e: 2, k: "people", d: "One who cares for the sick, and to hold something carefully." },
  OCEANIA: { e: 3, k: "continent", d: "Australia and the islands of the Pacific." },
  OCTOPUS: { e: 3, k: "animal", d: "Eight arms, three hearts, and a talent for escape." },
  ONION: { e: 3, k: "food", d: "The vegetable in layers, and the reason for the tears." },
  ORANGE: { e: 3, k: "food", d: "A citrus fruit, and the colour named after it." },
  ORCHARD: { e: 2, k: "nature", d: "A field of fruit trees, planted in rows. Obstgarten, verger, frutteto." },
  OVEN: { e: 3, k: "food", d: "The hot box that makes bread out of dough." },
  OWL: { e: 3, k: "animal", d: "The night hunter, silent in flight." },
  PAGE: { e: 3, k: "art", d: "One side of one leaf, numbered so it can be found again." },
  PAINT: { e: 2, k: "art", d: "Colour in a liquid, and to put it on." },
  PAINTER: { e: 2, k: "people", d: "One who paints, whether pictures or walls." },
  PAKISTAN: { e: 2, k: "country", d: "South Asia. Capital Islamabad. About 250 million people." },
  PAPER: { e: 3, k: "thing", d: "What was written on before screens; also a newspaper, and an essay." },
  PARIS: { e: 3, k: "city", d: "France's capital, on the Seine. The Eiffel Tower was meant to be temporary." },
  PARROT: { e: 3, k: "animal", d: "A bird that repeats what it hears." },
  PASTEUR: { e: 2, k: "figure", d: "French chemist, 1822-1895. Germ theory, vaccines, and the heating named after him." },
  PATH: { e: 3, k: "travel", d: "The unmade one." },
  PEACE: { e: 1, k: "idea", d: "Its absence, which has to be built." },
  PEN: { e: 3, k: "thing", d: "What ink comes out of; also an enclosure for animals." },
  PENCIL: { e: 3, k: "thing", d: "Graphite in wood, and the only writing that rubs out." },
  PENGUIN: { e: 3, k: "animal", d: "A bird that swims instead of flying. Southern hemisphere, always." },
  PEPPER: { e: 3, k: "food", d: "The spice that started the spice trade; also the vegetable." },
  PERU: { e: 3, k: "country", d: "Western South America, and the Inca before that. Capital Lima. About 34 million people." },
  PIANO: { e: 2, k: "art", d: "Eighty-eight keys; also, in music, quietly." },
  PICASSO: { e: 2, k: "figure", d: "Spanish painter, 1881-1973. Cubism, and about fifty thousand works." },
  PIG: { e: 3, k: "animal", d: "Kept for pork; cleverer than its reputation." },
  PIRATE: { e: 2, k: "people", d: "A thief at sea, and one who copies without paying." },
  PLANE: { e: 3, k: "travel", d: "An aircraft; also a flat surface, and a tool that flattens wood." },
  PLATE: { e: 3, k: "food", d: "What food is served on; also a thin sheet of metal or glass." },
  POET: { e: 2, k: "people", d: "One who writes verse, and is read afterwards." },
  POLAND: { e: 3, k: "country", d: "Central Europe. Capital Warsaw. About 37 million people." },
  PORTUGAL: { e: 3, k: "country", d: "The western edge of Europe. Capital Lisbon. About 10 million people." },
  POTATO: { e: 3, k: "food", d: "The tuber that changed what Europe could feed." },
  PRAGUE: { e: 2, k: "city", d: "The Czech capital, on the Vltava, with a bridge full of statues." },
  PRICE: { e: 1, k: "idea", d: "What a thing costs, and what it costs you." },
  PRINTER: { e: 3, k: "thing", d: "The machine that prints; and, for four hundred years before the machine, the person who did." },
  PROFIT: { e: 1, k: "idea", d: "What is left after everything is paid." },
  PROOF: { e: 2, k: "art", d: "A trial sheet pulled to be read for errors before the run.  Also: what settles an argument." },
  PULP: { e: 3, k: "thing", d: "Anything beaten wet and soft enough to be poured; paper begins here." },
  PUMP: { e: 3, k: "thing", d: "What moves liquid uphill; also a light shoe." },
  PUZZLE: { e: 1, k: "idea", d: "A problem set for the pleasure of solving it." },
  PYRAMID: { e: 3, k: "thing", d: "A solid with a square base and four triangular faces; in Egypt, a tomb." },
  QUEEN: { e: 2, k: "people", d: "The woman who rules, and the strongest piece in chess." },
  RABBIT: { e: 3, k: "animal", d: "Fast, timid, and famous for arithmetic." },
  RADIO: { e: 3, k: "thing", d: "Sound sent without a wire." },
  RAG: { e: 3, k: "thing", d: "A torn scrap of cloth. Paper was made of it for seventeen centuries before anyone tried wood." },
  RAIL: { e: 3, k: "travel", d: "An iron bar laid end to end with others, so that a wheel has only one choice." },
  RAIN: { e: 3, k: "nature", d: "Water falling out of that cloud." },
  RAINBOW: { e: 3, k: "nature", d: "Sunlight taken apart by rain." },
  RAT: { e: 3, k: "animal", d: "A larger rodent, blamed for a great deal, some of it fairly." },
  READER: { e: 3, k: "people", d: "Anyone who reads; and, in a printing house, the one paid to read for mistakes." },
  REEF: { e: 3, k: "nature", d: "A ridge of rock or coral just under the surface, waiting." },
  REMBRANDT: { e: 2, k: "figure", d: "Dutch painter, 1606-1669. Light, dark, and about eighty self-portraits." },
  RICE: { e: 3, k: "food", d: "The grain that feeds the most people." },
  RIDDLE: { e: 1, k: "idea", d: "A question made hard on purpose." },
  ROAD: { e: 3, k: "travel", d: "The made way between two places." },
  ROCKET: { e: 3, k: "travel", d: "The engine that carries its own air, and can therefore leave." },
  ROOF: { e: 3, k: "thing", d: "What keeps the rain out." },
  ROOT: { e: 3, k: "nature", d: "What holds a plant down and feeds it; also the origin of a word." },
  ROPE: { e: 3, k: "thing", d: "Fibres twisted until they can be trusted with weight." },
  RUSSIA: { e: 3, k: "country", d: "The largest country on earth, across Europe and Asia. Capital Moscow. About 144 million people." },
  SAIL: { e: 3, k: "travel", d: "Cloth that catches wind, and to travel by it." },
  SAILOR: { e: 3, k: "travel", d: "One who works a ship." },
  SALTWATER: { e: 3, k: "nature", d: "Water with the sea in it." },
  SAND: { e: 3, k: "nature", d: "Rock ground down until it pours." },
  SAW: { e: 3, k: "thing", d: "The toothed blade for cutting wood; also an old saying." },
  SCOOP: { e: 2, k: "idea", d: "A story nobody else has yet. Also a deep spoon, which is where the sense comes from." },
  SCOTLAND: { e: 3, k: "country", d: "The northern part of Britain. Capital Edinburgh. About 5.5 million people." },
  SCREW: { e: 3, k: "thing", d: "The thread that pulls itself in; also a ship's propeller." },
  SEABED: { e: 3, k: "nature", d: "The floor of the sea." },
  SEAM: { e: 2, k: "nature", d: "A band of one mineral lying flat between two others, and worth following." },
  SECRET: { e: 1, k: "idea", d: "What is known and not told." },
  SEED: { e: 3, k: "nature", d: "The small hard beginning of a plant." },
  SEOUL: { e: 2, k: "city", d: "South Korea's capital, on the Han." },
  SHADOW: { e: 3, k: "nature", d: "The shape of what stood in the light's way." },
  SHADOWPLAY: { e: 1, k: "idea", d: "Figures made of shadow, told as a story." },
  SHAFT: { e: 3, k: "thing", d: "A hole sunk straight down, and the only way in or out of what is below it." },
  SHAKESPEARE: { e: 2, k: "figure", d: "English playwright, 1564-1616. Thirty-seven plays and a great deal of the language." },
  SHANGHAI: { e: 3, k: "city", d: "China's largest city, on the delta of the Yangtze." },
  SHARK: { e: 3, k: "animal", d: "The oldest and least reassuring fish." },
  SHEEP: { e: 3, k: "animal", d: "Kept for wool and mutton; the reason for most walls." },
  SHIP: { e: 3, k: "travel", d: "A large one, that crosses." },
  SHOE: { e: 3, k: "thing", d: "What the foot wears, and what a horse is shod with." },
  SHORE: { e: 3, k: "nature", d: "Where the land agrees to stop." },
  SHOULDER: { e: 3, k: "body", d: "The joint at the top of the arm, and the edge of a road." },
  SILVER: { e: 3, k: "nature", d: "The second metal, and the colour of the moon." },
  SKETCH: { e: 2, k: "art", d: "A drawing done quickly, and a short comic scene." },
  SKIN: { e: 3, k: "body", d: "The body's outer layer, and the surface of anything." },
  SKY: { e: 3, k: "nature", d: "Everything above your head that is not ground." },
  SMITH: { e: 2, k: "people", d: "One who works metal, and the commonest surname in English." },
  SMOKE: { e: 3, k: "nature", d: "What fire sends up instead of light." },
  SNAKE: { e: 3, k: "animal", d: "A reptile that manages without legs." },
  SNOW: { e: 3, k: "nature", d: "Rain that took a colder route down." },
  SOIL: { e: 3, k: "nature", d: "The top few inches of the earth, which everything else depends on. Also, as a verb, to dirty." },
  SONG: { e: 2, k: "art", d: "Words and a tune, and the shortest way into a memory." },
  SOOT: { e: 3, k: "nature", d: "The black that smoke leaves behind when it has finished being smoke." },
  SOUP: { e: 3, k: "food", d: "Anything simmered long enough to agree with itself." },
  SPAIN: { e: 3, k: "country", d: "The larger part of the Iberian peninsula. Capital Madrid. About 48 million people." },
  SPARK: { e: 3, k: "nature", d: "The smallest possible fire, and the start of a larger one." },
  SPARROW: { e: 3, k: "animal", d: "The small brown bird that is everywhere and noticed nowhere." },
  SPEED: { e: 1, k: "idea", d: "Distance over time." },
  SPHINX: { e: 2, k: "thing", d: "A lion with a human head. In Egypt, carved at Giza; in Greece, it asked riddles." },
  SPIDER: { e: 3, k: "animal", d: "Eight legs, and a web to sit in the middle of." },
  SPOON: { e: 3, k: "food", d: "The tool for what a fork cannot hold." },
  SPY: { e: 2, k: "people", d: "One who gathers what was not offered." },
  SQUIRREL: { e: 3, k: "animal", d: "The rodent that buries nuts and forgets some, planting trees." },
  STAGE: { e: 2, k: "art", d: "Where a play happens; also a step in a process, and a leg of a race." },
  STAIR: { e: 3, k: "thing", d: "The way up, one step at a time." },
  STAR: { e: 3, k: "nature", d: "A sun seen from very far away. Also anyone the crowd looks up at." },
  STATION: { e: 3, k: "travel", d: "Where trains stop; also a post, and one's standing." },
  STATUE: { e: 2, k: "art", d: "A person kept in stone." },
  STEAM: { e: 3, k: "nature", d: "Water that has been given enough heat to push back." },
  STOCKHOLM: { e: 2, k: "city", d: "Sweden's capital, spread over fourteen islands." },
  STONE: { e: 3, k: "nature", d: "A piece of rock small enough to lift, or a whole mass of it." },
  STORM: { e: 3, k: "nature", d: "Wind and rain arriving together and in a hurry." },
  STORY: { e: 1, k: "idea", d: "Events told in an order that means something." },
  STREAM: { e: 3, k: "nature", d: "A small river, and any steady flow." },
  SUGAR: { e: 3, k: "food", d: "Sweetness, refined out of cane or beet." },
  SUMMER: { e: 1, k: "idea", d: "The warm quarter." },
  SWAMP: { e: 3, k: "nature", d: "Ground that has not decided whether it is water." },
  SWAN: { e: 3, k: "animal", d: "The white water bird that only sings once, if you believe the story." },
  SWEDEN: { e: 3, k: "country", d: "Scandinavia. Capital Stockholm. About 10.6 million people." },
  SWITZERLAND: { e: 3, k: "country", d: "The Alps, and four national languages. Capital Bern. About 9 million people." },
  SYDNEY: { e: 3, k: "city", d: "Australia's largest city, around a harbour, with an opera house on it. Not the capital." },
  TAX: { e: 1, k: "idea", d: "The state's share, taken first." },
  TEA: { e: 3, k: "food", d: "Dried leaf in hot water; the reason for several wars." },
  TEAM: { e: 2, k: "people", d: "People who win or lose together." },
  TELEPHONE: { e: 3, k: "thing", d: "Speech sent along one." },
  TELESCOPE: { e: 3, k: "thing", d: "The tube that makes far things near." },
  TENT: { e: 3, k: "thing", d: "A house that folds." },
  TESLA: { e: 2, k: "figure", d: "Serbian-American engineer, 1856-1943. Alternating current, which is why your wall works." },
  THAILAND: { e: 3, k: "country", d: "South-east Asia. Capital Bangkok. About 72 million people." },
  THEATRE: { e: 2, k: "art", d: "The building for plays, and the room for operations." },
  THIEF: { e: 2, k: "people", d: "One who takes what is not theirs." },
  THORN: { e: 3, k: "nature", d: "A plant's answer to being eaten." },
  THREAD: { e: 3, k: "thing", d: "Spun fibre; also a line of argument, or of messages." },
  THUMB: { e: 3, k: "body", d: "The finger that made tools possible." },
  THUNDER: { e: 3, k: "nature", d: "The sound lightning makes after the fact." },
  TICKET: { e: 3, k: "travel", d: "Proof you paid to travel." },
  TIDE: { e: 3, k: "nature", d: "The sea rising and falling, twice a day, because of the moon." },
  TIGER: { e: 3, k: "animal", d: "The big cat that does not." },
  TIME: { e: 1, k: "idea", d: "The one thing nobody has found a way to make more of." },
  TOKYO: { e: 3, k: "city", d: "Japan's capital, and the largest metropolitan area in the world." },
  TOLSTOY: { e: 2, k: "figure", d: "Russian novelist, 1828-1910. War and Peace, Anna Karenina." },
  TOMATO: { e: 3, k: "food", d: "A fruit that insists on being treated as a vegetable." },
  TORONTO: { e: 2, k: "city", d: "Canada's largest city, on Lake Ontario." },
  TRADE: { e: 1, k: "idea", d: "Exchange, and the craft one is trained in." },
  TREE: { e: 3, k: "nature", d: "A tall woody plant; also any branching diagram." },
  TRUMPET: { e: 2, k: "art", d: "Brass, three valves, and no way to play it discreetly." },
  TRUTH: { e: 1, k: "idea", d: "What is the case, whoever it suits." },
  TURING: { e: 2, k: "figure", d: "English mathematician, 1912-1954. Broke Enigma, and defined what a computer is." },
  TURKEY: { e: 3, k: "country", d: "Across Europe and Asia. Capital Ankara, though Istanbul is larger. About 85 million people." },
  TURTLE: { e: 3, k: "animal", d: "A reptile that carries its house." },
  TWIG: { e: 3, k: "nature", d: "The thinnest branch. Also, in British slang, to catch on." },
  TYPE: { e: 2, k: "art", d: "A letter cast in metal, back to front, to be inked and pressed. Cut once, set again for ever." },
  VALLEY: { e: 3, k: "nature", d: "The low ground between hills, usually with water in it." },
  VALVE: { e: 3, k: "thing", d: "What lets flow go one way only; also part of a trumpet, and a heart." },
  VENICE: { e: 3, k: "city", d: "Italy, built on a lagoon and a hundred islands, with canals for streets." },
  VERDI: { e: 2, k: "figure", d: "Italian composer, 1813-1901. Opera, and a national anthem's worth of choruses." },
  VERSE: { e: 2, k: "art", d: "A stanza, and poetry generally." },
  VIENNA: { e: 3, k: "city", d: "Austria's capital, on the Danube. Mozart, Beethoven and Freud all worked here." },
  VIETNAM: { e: 3, k: "country", d: "South-east Asia. Capital Hanoi. About 100 million people." },
  VIOLIN: { e: 2, k: "art", d: "Four strings and a bow, at the front of the orchestra." },
  VOICE: { e: 3, k: "body", d: "The sound a person makes, and their say in a matter." },
  VOLCANO: { e: 3, k: "nature", d: "A mountain with a way out for what is under it." },
  VOLTA: { e: 2, k: "figure", d: "Italian physicist, 1745-1827. Built the first battery; the volt is his." },
  WALL: { e: 3, k: "thing", d: "What keeps everything else out." },
  WAR: { e: 1, k: "idea", d: "Organised violence between states." },
  WATER: { e: 3, k: "nature", d: "The liquid everything alive is mostly made of. Also, as a verb, what you do to a garden." },
  WATT: { e: 2, k: "figure", d: "Scottish engineer, 1736-1819. Made the steam engine efficient; the unit of power is his." },
  WEB: { e: 3, k: "animal", d: "What the spider builds; also the thing you are reading this on." },
  WEIGHT: { e: 1, k: "idea", d: "How hard gravity is pulling, and how much a thing matters." },
  WHALE: { e: 3, k: "animal", d: "The largest animal there has ever been, and a mammal at that." },
  WHEEL: { e: 3, k: "thing", d: "The invention everything else is bolted to." },
  WINDOW: { e: 3, k: "thing", d: "A hole for light, glazed; also a period when something is possible." },
  WINE: { e: 3, k: "food", d: "Fermented grape juice, and the oldest reason to keep a cellar." },
  WINTER: { e: 1, k: "idea", d: "The cold one, and any bleak stretch." },
  WITCH: { e: 2, k: "people", d: "A woman said to have power, and burned for the saying." },
  WOLF: { e: 3, k: "animal", d: "The wild dog that would not come inside." },
  WORM: { e: 3, k: "animal", d: "The animal that eats the soil and improves it." },
  WRECK: { e: 3, k: "travel", d: "A ship that lost, and what is left of it." },
  WRIGHT: { e: 2, k: "figure", d: "American brothers, Wilbur and Orville. First powered flight, 1903." },
  YEAR: { e: 1, k: "idea", d: "One trip round the sun." },
  YEAST: { e: 3, k: "food", d: "The living thing that makes bread rise and beer possible." },
  ZEBRA: { e: 3, k: "animal", d: "A horse that settled the argument about stripes." }
};
