# -*- coding: utf-8 -*-
# Polysemous English words for Crosslink. Each entry: (word, [(domain, gloss)...], note)
# Ranked downstream by the number of DISTINCT domains, not by raw sense count.

WORDS = [
("PITCH", [("Sport","a throw, and the field played on"),("Music","how high a note sounds"),("Substance","black tar; pitch-black"),("Trade","a sales pitch"),("Building","the slope of a roof"),("Action","to pitch a tent"),("Nautical","a ship pitching in swell")],
 "Music and Substance are the cleanest pair: a note and a tar have nothing to say to each other."),
("STOCK", [("Food","the broth a soup is built on"),("Money","shares in a company"),("Animal","livestock"),("Military","the wooden part of a gun"),("Abstract","descent, as in 'of good stock'"),("Trade","goods held in reserve"),("Plant","the flower, and a grafting rootstock"),("Law","the stocks, a punishment")],
 "Food and Money in one square. SOUP on one side, SHARE on the other."),
("BAR", [("Place","where drink is served"),("Artifact","a rod of metal"),("Music","a measure of written music"),("Law","the profession, and the bar of a court"),("Nature","a sandbar at a river mouth"),("Action","to bar the way"),("Measure","a bar of pressure")],
 "Music and Law is the elegant cross; Place and Nature is the funny one."),
("KEY", [("Artifact","what opens a lock"),("Music","the key a piece is written in"),("Tool","a piano or typewriter key"),("Language","a legend or answer key"),("Nature","a low island; the Florida Keys"),("Abstract","crucial, the key point")],
 "Lock and music and island. Three sturdy, unrelated referents."),
("BRIDGE", [("Building","the span over water"),("Game","the card game"),("Body","the bridge of the nose"),("Music","the piece under violin strings, and a song's middle section"),("Nautical","where a ship is commanded from"),("Science","dentistry; a dental bridge"),("Action","to bridge a gap")],
 "Six referents, all concrete. One of the strongest hinges in English."),
("HAND", [("Body","the end of the arm"),("Artifact","a clock hand"),("Game","the cards you hold"),("Person","a worker; all hands on deck"),("Language","handwriting"),("Action","applause; a big hand"),("Measure","the height of a horse")],
 "Body and Measure cross beautifully: HORSE and WRIST from one square."),
("HEAD", [("Body","what sits on the neck"),("Person","the person in charge"),("Food","the foam on a beer"),("Nautical","the lavatory on a boat"),("Nature","the source of a river, and a headland"),("Measure","cattle counted by the head"),("Action","to head somewhere")],
 "Nature and Food is the surprise: SOURCE and BEER."),
("STRIKE", [("Action","to hit"),("Trade","workers downing tools"),("Sport","in baseball, and in bowling"),("Money","to strike a coin"),("Nature","an oil strike; a discovery"),("Time","a clock striking the hour"),("Military","an air strike")],
 "Money and Trade sit oddly together: MINT strikes a COIN, UNION calls a STRIKE."),
("RING", [("Shape","a circle"),("Artifact","jewellery for a finger"),("Music","the sound a bell makes"),("Sport","where boxers fight"),("Group","a criminal ring"),("Language","a telephone call"),("Plant","the growth rings of a tree")],
 "Plant and Music: TREE on one axis, BELL on the other."),
("SHOT", [("Military","a fired round"),("Art","a photograph or a camera shot"),("Science","an injection"),("Abstract","an attempt; give it a shot"),("Drink","a small measure of spirits"),("Substance","lead pellets"),("Sport","the shot put")],
 "Drink and Science: WHISKY and VACCINE, same four letters."),
("CHARGE", [("Money","a fee"),("Science","electrical charge"),("Military","a cavalry charge"),("Law","a criminal charge"),("Person","someone in your care"),("Action","to load a weapon or a battery")],
 "Science and Law cross cleanly: ELECTRON and CRIME."),
("CELL", [("Building","a room in a prison, and a monk's room"),("Science","the unit of life"),("Artifact","a battery cell"),("Group","a resistance or terrorist cell"),("Language","a cell in a spreadsheet or table"),("Body","a blood cell")],
 "Prison and biology. MONK and NUCLEUS from the same square."),
("MOLE", [("Animal","the burrowing creature"),("Body","a dark mark on skin"),("Person","a spy inside an organisation"),("Measure","the chemist's unit of quantity"),("Building","a breakwater or pier"),("Food","the Mexican sauce")],
 "Animal, spy, chemistry, sauce. Almost too good; use one pairing, not four."),
("SHELL", [("Animal","what a mollusc lives in"),("Military","artillery ammunition"),("Building","the frame of a building"),("Food","a pastry case"),("Science","an electron shell"),("Language","a command shell")],
 "Animal and Military: SNAIL and CANNON."),
("TRUNK", [("Plant","the stem of a tree"),("Animal","an elephant's nose"),("Artifact","a travelling chest"),("Vehicle","the boot of a car"),("Body","the torso"),("Place","a trunk road or trunk line")],
 "Plant and Animal in one word is rare and very usable."),
("WING", [("Animal","what a bird flies with"),("Vehicle","an aircraft wing"),("Building","a wing of a house"),("Abstract","a political wing"),("Place","the wings of a theatre"),("Sport","a winger's position")],
 "Animal and Building: SPARROW and HOSPITAL."),
("CRACK", [("Shape","a fissure"),("Music","a sharp sound"),("Language","a joke; to crack wise"),("Substance","the drug"),("Abstract","an attempt; have a crack"),("Attribute","expert; a crack shot")],
 None),
("CROWN", [("Artifact","what a monarch wears"),("Body","the top of the head"),("Science","a cap on a tooth"),("Money","the coin, and the currency"),("Plant","the top of a tree"),("Law","the Crown as the state")],
 "Money and Plant: COIN and CANOPY."),
("LEAD", [("Substance","the soft grey metal"),("Action","to guide"),("Artifact","a dog's lead"),("Abstract","a clue for an investigator"),("Sport","the front position"),("Tool","the graphite in a pencil")],
 "Two pronunciations, which the board cannot show. Free difficulty."),
("SCALE", [("Animal","what covers a fish"),("Tool","the instrument that weighs"),("Music","the ladder of notes"),("Measure","a map's ratio"),("Action","to climb"),("Substance","limescale in a kettle")],
 "Animal and Music: CARP and OCTAVE."),
("DRAUGHT", [("Nature","a current of air"),("Drink","beer served from the cask"),("Military","conscription (US draft)"),("Language","a preliminary version"),("Nautical","how deep a ship sits"),("Animal","a draught horse"),("Game","the game of draughts")],
 "Spelling splits UK/US, which is itself a clue worth using."),
("FIGURE", [("Measure","a number"),("Body","the shape of a person"),("Person","a notable person"),("Language","an illustration in a book"),("Action","to reckon; I figure"),("Art","a figure in a dance")],
 None),
("RUN", [("Action","to move fast on foot"),("Textile","a ladder in a stocking"),("Sport","a run in cricket or baseball"),("Trade","to run a business"),("Nature","a stream; a salmon run"),("Language","a print run")],
 None),
("CAPITAL", [("Place","the chief city"),("Money","funds and assets"),("Language","an upper-case letter"),("Building","the carved top of a column"),("Law","punishable by death")],
 "Building and Language is the best cross: COLUMN and LETTER."),
("COURT", [("Law","where a case is heard"),("Group","a monarch's household"),("Sport","where tennis is played"),("Place","a courtyard"),("Action","to court someone")],
 "Law and Sport: JUDGE and TENNIS."),
("CLUB", [("Artifact","a heavy stick"),("Group","a society"),("Place","a nightclub"),("Sport","a golf club"),("Game","the card suit")],
 None),
("PORT", [("Place","a harbour"),("Drink","the fortified wine"),("Nautical","the left side of a ship"),("Language","a socket on a machine"),("Action","to port software across")],
 "Place and Drink: HARBOUR and WINE, which are also historically the same thing."),
("BAY", [("Nature","an inlet of the sea"),("Plant","the laurel; bay leaves"),("Animal","a reddish-brown horse"),("Action","to howl; hounds baying"),("Building","a loading bay or bay window")],
 "Nature and Plant and Animal. A rare three-way among concrete things."),
("BILL", [("Money","an invoice, and a banknote"),("Animal","a bird's beak"),("Law","a proposed act of parliament"),("Language","a poster; to bill a show"),("Textile","the brim of a cap")],
 "Animal and Law: DUCK and PARLIAMENT."),
("BOARD", [("Artifact","a plank of wood"),("Group","the directors of a company"),("Food","meals; room and board"),("Action","to board a ship"),("Game","the surface a game is played on")],
 None),
("BOLT", [("Artifact","a threaded fastener"),("Nature","a bolt of lightning"),("Action","to bolt; to run away"),("Textile","a roll of cloth"),("Military","a crossbow bolt")],
 "Artifact and Nature: NUT and LIGHTNING."),
("SOUND", [("Music","what the ear hears"),("Attribute","solid, healthy, sound reasoning"),("Nature","a strait of water; Puget Sound"),("Nautical","to sound the depth"),("Action","to sound out")],
 "Music and Nature: NOISE and STRAIT."),
("SPRING", [("Time","the season"),("Nature","water rising from the ground"),("Artifact","a coil of metal"),("Action","to leap"),("Abstract","the origin of a thing")],
 "Time and Artifact: MARCH and WATCH."),
("BANK", [("Nature","the edge of a river"),("Money","where money is kept"),("Artifact","a bank of oars, lights, switches"),("Action","to bank an aircraft"),("Abstract","to bank on something")],
 "The classic. Nature and Money: RIVER and VAULT."),
("TABLE", [("Artifact","the furniture"),("Language","a grid of data"),("Nature","a tableland or plateau; the water table"),("Law","to table a motion"),("Food","the table one eats at")],
 None),
("HOST", [("Person","one who receives guests"),("Measure","a great multitude"),("Science","the organism a parasite lives on"),("Religion","the communion wafer"),("Military","an army; the heavenly host")],
 "Person and Science: GUEST and PARASITE."),
("MEDIUM", [("Measure","the middle size"),("Person","one who speaks to the dead"),("Language","a means of communication"),("Art","the material an artist works in"),("Science","a growth medium")],
 None),
("BATTERY", [("Artifact","what stores charge"),("Law","assault and battery"),("Military","a group of guns"),("Sport","the pitcher and catcher together"),("Abstract","a battery of tests")],
 "Artifact and Law: TORCH and ASSAULT."),
("COMPOUND", [("Science","a chemical combination"),("Place","a walled enclosure"),("Action","to make worse; to compound a problem"),("Language","a compound word"),("Money","compound interest")],
 "Science and Place: MOLECULE and FENCE."),
("BEAR", [("Animal","the large mammal"),("Action","to carry"),("Abstract","to endure"),("Money","a falling market"),("Science","to give birth to")],
 "Animal and Money: FOREST and MARKET, with BULL waiting in the next square."),
("BULL", [("Animal","the male of cattle"),("Money","a rising market"),("Religion","a papal bull"),("Abstract","nonsense"),("Sport","the bullseye")],
 "Pair it with BEAR on the same board and the market does the crossing."),
("HORN", [("Body","what grows on a bull's head"),("Music","the brass instrument"),("Artifact","a car horn"),("Nature","a cape; Cape Horn"),("Drink","a drinking horn")],
 None),
("EYE", [("Body","the organ of sight"),("Tool","the eye of a needle"),("Nature","the calm centre of a storm"),("Plant","the eye of a potato"),("Textile","a hook and eye")],
 "Body and Tool: SIGHT and NEEDLE."),
("TONGUE", [("Body","the organ in the mouth"),("Language","a language; the mother tongue"),("Textile","the flap under a shoelace"),("Nature","a spit of land"),("Artifact","the clapper of a bell")],
 "Body and Language, which is the same metaphor made literal. Very Crosslink."),
("BOW", [("Military","the weapon that fires arrows"),("Music","what draws across violin strings"),("Textile","a tied ribbon"),("Action","to bend at the waist"),("Nautical","the front of a ship")],
 "Also two pronunciations. Pair it with STERN and the ship sense locks."),
("CHIP", [("Food","a fried potato"),("Science","a silicon chip"),("Game","a gambling token"),("Object","a fragment broken off"),("Sport","a chip shot")],
 "Food and Science: POTATO and SILICON."),
("JAM", [("Food","fruit preserve"),("Vehicle","a traffic jam"),("Action","to wedge tight"),("Music","a jam session"),("Abstract","a difficulty; in a jam")],
 "Food and Music: TOAST and SESSION."),
("PAN", [("Artifact","the cooking vessel"),("Language","to pan a film; to criticise"),("Art","a camera pan"),("Action","to pan for gold"),("Nature","a salt pan")],
 None),
("FILE", [("Artifact","a folder of papers"),("Tool","the metal rasp"),("Group","a line of people; single file"),("Game","a column on a chessboard"),("Law","to file a claim")],
 "Artifact and Tool: PAPER and RASP."),
("TRAIN", [("Vehicle","the thing on rails"),("Action","to teach by repetition"),("Textile","the trailing part of a dress"),("Abstract","a train of thought"),("Group","a retinue")],
 None),
("CASE", [("Artifact","a container"),("Law","a legal matter"),("Language","the grammatical case; nominative, dative"),("Science","a patient"),("Abstract","an instance")],
 "Law and Language: TRIAL and DATIVE."),
("CHECK", [("Action","to verify"),("Game","in chess"),("Money","the bill, and the cheque"),("Textile","the pattern"),("Language","the tick mark")],
 "Game and Textile: CHESS and TARTAN."),
("TIP", [("Shape","the pointed end"),("Money","a gratuity"),("Language","a piece of advice"),("Action","to tilt over"),("Place","a rubbish tip")],
 None),
("FOOT", [("Body","the end of the leg"),("Measure","twelve inches"),("Language","a metrical foot in verse"),("Place","the foot of a hill or a bed")],
 "Body and Measure and Language, all three respectable."),
("SPIRIT", [("Religion","the soul, and a ghost"),("Drink","distilled alcohol"),("Abstract","morale; team spirit"),("Science","a volatile solvent")],
 "Religion and Drink: GHOST and GIN."),
("GUM", [("Food","chewing gum"),("Body","the flesh around teeth"),("Plant","tree resin; a gum tree"),("Substance","adhesive")],
 None),
("LOG", [("Plant","a felled length of tree"),("Language","a written record"),("Measure","a logarithm"),("Nautical","a ship's log and log-line")],
 "Plant and Language: TIMBER and DIARY, and they are the same word by history."),
("SEAL", [("Animal","the sea mammal"),("Artifact","a stamp pressed into wax"),("Action","to close something tight"),("Tool","a gasket or washer")],
 "Animal and Artifact: WALRUS and WAX."),
("KID", [("Person","a child"),("Animal","a young goat"),("Textile","soft leather; kid gloves"),("Action","to joke; you're kidding")],
 "Person and Animal and Textile, and all three are the same animal by history."),
("SOLE", [("Body","the underside of the foot"),("Textile","the underside of a shoe"),("Animal","the flatfish"),("Attribute","only; the sole survivor")],
 "Animal and Body: PLAICE and FOOT."),
("MINT", [("Plant","the herb"),("Money","where coins are struck"),("Attribute","perfect; mint condition"),("Food","a boiled sweet")],
 "Plant and Money: TEA and COIN. The example that started this."),
("PLANT", [("Plant","a growing thing"),("Building","a factory"),("Action","to put a seed in the ground"),("Person","an informer placed inside")],
 None),
("MATCH", [("Artifact","the small fire-stick"),("Sport","a contest"),("Abstract","an equal or a pair"),("Person","a marriage match")],
 "Artifact and Sport: FLAME and FOOTBALL."),
("SUBJECT", [("Abstract","the topic at hand"),("Person","a citizen of a monarch"),("Language","the subject of a sentence"),("Science","a person in an experiment")],
 "Language and Person: VERB and MONARCH."),
("PRESENT", [("Object","a gift"),("Time","now"),("Action","to introduce or hand over"),("Attribute","in attendance")],
 "Time and Object, and the stress moves. PRESent and preSENT."),
("SECOND", [("Time","one sixtieth of a minute"),("Measure","the one after first"),("Law","to second a motion"),("Person","the assistant at a duel")],
 "Time and Measure, and the two are historically the same idea."),
("POUND", [("Measure","a unit of weight"),("Money","the currency"),("Action","to beat repeatedly"),("Place","where stray dogs are kept")],
 "Money and Place: STERLING and DOG."),
("CHAIR", [("Artifact","the furniture"),("Person","who runs a meeting"),("Abstract","a professorship"),("Law","the electric chair")],
 None),
("COMPANY", [("Trade","a business"),("Group","guests; we have company"),("Military","a unit of soldiers"),("Art","a theatre or dance company")],
 None),
("ORGAN", [("Body","the heart, the liver"),("Music","the instrument with pipes"),("Language","a newspaper; the party organ"),("Group","a part of an institution")],
 "Body and Music: LIVER and PIPE."),
("NOTE", [("Music","a single sound"),("Language","a written message"),("Money","a banknote"),("Action","to notice")],
 "Music and Money: OCTAVE and TENNER."),
("SPINE", [("Body","the backbone"),("Artifact","the edge of a book"),("Plant","a thorn"),("Abstract","courage")],
 "Body and Artifact: VERTEBRA and BOOK."),
("NECK", [("Body","between head and shoulders"),("Artifact","the neck of a bottle"),("Music","the neck of a guitar"),("Nature","an isthmus")],
 None),
("HEEL", [("Body","the back of the foot"),("Textile","the back of a shoe"),("Food","the end slice of a loaf"),("Person","a cad")],
 None),
("LEG", [("Body","what you stand on"),("Artifact","a table leg"),("Sport","one stage of a journey or a tie"),("Game","the leg side in cricket")],
 None),
("PLOT", [("Language","the story of a novel"),("Place","a parcel of land"),("Abstract","a conspiracy"),("Measure","to plot on a graph")],
 "Language and Place: NOVEL and GRAVEYARD."),
("SPELL", [("Religion","words of magic"),("Language","to give the letters in order"),("Time","a period; a cold spell"),("Trade","a turn at work")],
 "Religion and Language: WITCH and ALPHABET."),
("POST", [("Artifact","an upright timber"),("Language","the mail, and to publish"),("Person","a job or position"),("Military","a station one is posted to")],
 None),
("LIGHT", [("Nature","what the sun gives"),("Measure","not heavy"),("Action","to set alight"),("Attribute","pale in colour")],
 "Nature and Measure: SUN and FEATHER."),
("FAIR", [("Abstract","just"),("Attribute","light in colour"),("Trade","a market or funfair"),("Nature","fine weather")],
 None),
("FINE", [("Attribute","excellent"),("Law","a money penalty"),("Measure","thin or delicate"),("Nature","clear weather")],
 "Attribute and Law: EXCELLENT and PENALTY, which are opposites in feeling."),
("MEAN", [("Measure","the average"),("Language","to signify"),("Attribute","unkind"),("Action","to intend")],
 None),
("SUIT", [("Textile","the set of clothes"),("Game","the card suit"),("Law","a lawsuit"),("Action","to be fitting; it suits you")],
 None),
("HEART", [("Body","the organ"),("Game","the card suit"),("Abstract","courage; take heart"),("Place","the centre; the heart of the city")],
 None),
("DIAMOND", [("Substance","the gem"),("Game","the card suit"),("Sport","the baseball infield"),("Shape","the rhombus")],
 None),
("POT", [("Artifact","the cooking vessel"),("Substance","cannabis"),("Game","the stake in a card game"),("Sport","to pot a ball")],
 None),
("PRESS", [("Action","to push"),("Language","newspapers collectively"),("Artifact","the printing machine"),("Sport","a weightlifting press")],
 None),
("LAP", [("Body","the thighs when seated"),("Sport","one circuit of a track"),("Action","to drink as a cat does"),("Shape","an overlap")],
 None),
("BUFF", [("Attribute","the pale yellow colour"),("Person","an enthusiast"),("Action","to polish"),("Textile","buff leather")],
 None),
("CONSOLE", [("Action","to comfort"),("Artifact","a control panel"),("Game","a games console"),("Building","a bracket or console table")],
 None),
("TURKEY", [("Place","the country"),("Animal","the bird"),("Abstract","a flop; a bad film"),("Sport","three strikes in bowling")],
 "The bird is named for the country by a mistake, which is a clue in itself."),
("DUCK", [("Animal","the water bird"),("Action","to dodge downward"),("Sport","a score of nought in cricket"),("Textile","a heavy cotton cloth")],
 None),
("CRAB", [("Animal","the shellfish"),("Plant","the crab apple"),("Action","to move sideways"),("Person","a bad-tempered one")],
 None),
("BUCK", [("Animal","a male deer"),("Money","a dollar"),("Action","to throw a rider"),("Abstract","responsibility; the buck stops here")],
 None),
("FAN", [("Artifact","what moves air"),("Person","an enthusiast"),("Shape","a fan shape"),("Action","to fan out")],
 "Artifact and Person, and they are the same word only by coincidence (fanatic)."),
("ROCK", [("Substance","stone"),("Music","the music"),("Action","to sway"),("Object","a diamond")],
 None),
("WAVE", [("Nature","water rising and falling"),("Action","a greeting with the hand"),("Science","in physics; light and sound"),("Body","a wave in the hair")],
 None),
("FLUKE", [("Abstract","a stroke of luck"),("Animal","the tail of a whale, and a parasitic worm"),("Nautical","the barb of an anchor")],
 None),
("DESERT", [("Nature","arid land"),("Action","to abandon"),("Abstract","what one deserves; just deserts")],
 "Stress moves between the first two. DESert and deSERT."),
("PALM", [("Body","the inside of the hand"),("Plant","the tree"),("Action","to conceal in the hand")],
 "Body and Plant: HAND and DATE."),
("IRIS", [("Body","the coloured ring of the eye"),("Plant","the flower"),("Artifact","a camera aperture")],
 "Body and Plant: PUPIL and PETAL."),
("TEMPLE", [("Building","a place of worship"),("Body","the side of the forehead"),("Artifact","the arm of a pair of spectacles")],
 "Building and Body: ALTAR and SKULL."),
("CALF", [("Animal","a young cow"),("Body","the muscle below the knee"),("Nature","an iceberg calving from a glacier")],
 "Animal and Body: COW and SHIN."),
("EAR", [("Body","the organ of hearing"),("Plant","an ear of corn"),("Music","a good ear; an ear for music")],
 "Body and Plant: HEARING and MAIZE."),
("SAGE", [("Plant","the herb"),("Person","a wise elder"),("Attribute","the grey-green colour")],
 "Plant and Person: THYME and PHILOSOPHER."),
("CULTURE", [("Group","the customs of a people"),("Science","bacteria grown in a dish"),("Art","the arts collectively")],
 "Group and Science: NATION and PETRI DISH."),
("MASS", [("Science","how much matter a thing has"),("Religion","the church service"),("Measure","a large quantity")],
 "Science and Religion: GRAVITY and CHURCH."),
("SEASON", [("Time","one of the four"),("Food","to add salt and spice"),("Trade","to age timber until it is ready")],
 "Time and Food: AUTUMN and PEPPER."),
("FAST", [("Measure","quick"),("Religion","to go without food"),("Attribute","firmly fixed; hold fast")],
 "Quick and abstaining and immovable. Two of the three are near-opposites."),
("CONTRACT", [("Law","a binding agreement"),("Action","to shrink"),("Science","to catch a disease")],
 "Law and Action: SIGNATURE and MUSCLE."),
("CURRENT", [("Nature","the flow of water"),("Science","the flow of electricity"),("Time","present-day")],
 None),
("GRAVE", [("Place","a burial place"),("Attribute","serious"),("Language","the accent mark; grave and acute")],
 None),
("STAPLE", [("Artifact","the wire fastener"),("Food","a basic foodstuff"),("Trade","a principal product")],
 "Artifact and Food: PAPER and RICE."),
("CHEST", [("Body","the ribcage"),("Artifact","a strong box"),("Building","a chest of drawers")],
 None),
("TOOTH", [("Body","what bites"),("Artifact","a tooth on a gear or comb"),("Tool","a saw tooth")],
 None),
("ARTICLE", [("Language","a piece of writing, and a, an, the"),("Object","a thing; an article of clothing"),("Law","a clause of a treaty")],
 None),
("VOLUME", [("Language","a book, one of several"),("Music","loudness"),("Measure","how much space a thing fills")],
 "Language and Measure: LIBRARY and LITRE."),
("MOUTH", [("Body","where food goes in"),("Nature","where a river meets the sea"),("Place","the entrance to a cave")],
 "Body and Nature: TEETH and DELTA."),
("SINK", [("Artifact","the basin"),("Action","to go under"),("Science","a heat sink")],
 None),
("WELL", [("Nature","a shaft sunk for water"),("Attribute","in good health"),("Building","a stairwell")],
 "Nature and Attribute: WATER and HEALTH."),
("STAMP", [("Language","what franks a letter"),("Action","to bring the foot down"),("Tool","the die that makes a mark")],
 None),
("YARD", [("Measure","three feet"),("Place","an enclosed space"),("Nautical","the spar a sail hangs from")],
 None),
("ROW", [("Shape","a line of things"),("Group","a quarrel"),("Action","to propel a boat with oars")],
 "Two pronunciations again. ROE is a homophone of one of them; keep them apart on a board."),
("LIE", [("Language","an untruth"),("Action","to be horizontal"),("Sport","where the golf ball sits")],
 None),
("MOMENT", [("Time","a short while"),("Science","turning force about a point"),("Abstract","importance; of great moment")],
 None),
("NAIL", [("Body","what grows on a finger"),("Artifact","the metal fastener"),("Action","to succeed; nailed it")],
 "Body and Artifact: THUMB and HAMMER."),
("ARMS", [("Body","the two limbs"),("Military","weapons"),("Abstract","a coat of arms")],
 None),
("JERSEY", [("Place","the Channel island"),("Textile","a knitted shirt"),("Animal","the breed of cow")],
 None),
("BAT", [("Animal","the flying mammal"),("Sport","what a batsman holds"),("Action","to bat an eyelid")],
 "Animal and Sport: CAVE and CRICKET."),
("MINUTE", [("Time","sixty seconds"),("Measure","tiny; a minute quantity"),("Language","the written record of a meeting")],
 "Pronounced two ways, spelled one. MINute and myNEWT."),
("OBJECT", [("Object","a thing"),("Action","to protest"),("Language","the object of a verb")],
 "Stress moves. OBject and obJECT."),
("SENTENCE", [("Language","a complete thought in words"),("Law","the punishment a judge gives")],
 "Only two, but perfectly clean: GRAMMAR and PRISON. Better than a word with seven mushy senses."),
("QUARRY", [("Place","where stone is cut"),("Animal","the hunted creature")],
 "Two domains, zero overlap, unrelated by origin. A model two-way hinge."),
("CABINET", [("Artifact","a cupboard"),("Group","the ministers of a government")],
 "MINISTER and DRAWER. Clean, and historically the same small room."),
("SOLUTION", [("Abstract","the answer to a problem"),("Science","a liquid with something dissolved in it")],
 "PUZZLE and SALT, which is a Crosslink joke waiting to happen."),
("PUPIL", [("Person","a student"),("Body","the opening in the eye")],
 "TEACHER and IRIS. Famous, and the two are the same word by origin."),
("CRANE", [("Animal","the long-legged bird"),("Artifact","the lifting machine"),("Action","to crane one's neck")],
 "The purest hinge in English: the machine is named for the bird. Two clean domains, no mush."),
("CHINA", [("Place","the country"),("Substance","porcelain")],
 "A place that became a material. See also JERSEY, DENIM, CASHMERE, TURKEY."),
("STERN", [("Nautical","the back of a ship"),("Attribute","severe")],
 "Put BOW in another square and the pair does the work."),
("REFRAIN", [("Action","to hold back from doing"),("Music","the repeated chorus")],
 None),
("STABLE", [("Building","where horses are kept"),("Attribute","steady, not liable to fall")],
 None),
("NOVEL", [("Language","a long work of fiction"),("Attribute","new and unusual")],
 None),
("PATIENT", [("Science","one under a doctor's care"),("Attribute","able to wait without complaint")],
 None),
("SPADE", [("Tool","the digging implement"),("Game","the card suit")],
 None),
("SEWER", [("Building","the drain under a city"),("Person","one who sews")],
 None),
("BASS", [("Music","the low register"),("Animal","the fish")],
 "Two pronunciations. GUITAR and TROUT."),
("SOW", [("Animal","a female pig"),("Action","to scatter seed")],
 "Two pronunciations, and the pair PIG / SEED is very clean."),
("WIND", [("Nature","moving air"),("Action","to turn a handle or a clock")],
 None),
("TEAR", [("Body","what falls from the eye"),("Action","to rip")],
 None),
]
